<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_home_token_0</name>
   <tag></tag>
   <elementGuidId>4d40bf10-0697-4005-a65d-c6c0bbca79f2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='home_token_0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#home_token_0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8f97617e-09ab-4ed7-bb40-0aa92bd9d4e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>home_token_0</value>
      <webElementGuid>e31e8864-cc87-4aa6-80e3-b0ad40b13763</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-mvs7qj</value>
      <webElementGuid>2211c54d-d9c5-46dd-8288-8b9a64239d89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>QC1QC1999.00 QC1</value>
      <webElementGuid>32388a51-6893-4dcd-9131-8173562ebad0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;home_token_0&quot;)</value>
      <webElementGuid>d516db6e-ff60-4e4f-9507-59c25ba0ff84</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='home_token_0']</value>
      <webElementGuid>ac6aca72-00c0-45b9-abe4-2f30e650b6f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tabs-:r1g:--tabpanel-0']/div/div</value>
      <webElementGuid>218fcc38-a5c3-4fac-8900-bc12d1a4d84e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SBTs'])[1]/following::div[4]</value>
      <webElementGuid>c38246d2-9207-49e9-8c9d-4c0d37178426</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NFTs'])[1]/following::div[5]</value>
      <webElementGuid>79dcade4-db37-4af0-87e8-9d6ac2abeaec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/div/div/div</value>
      <webElementGuid>57626318-e2f9-475c-a05d-a0326d726380</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'home_token_0' and (text() = 'QC1QC1999.00 QC1' or . = 'QC1QC1999.00 QC1')]</value>
      <webElementGuid>fe711bb4-b549-42f7-89fc-087cd451c7bf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
