<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_gas_fee</name>
   <tag></tag>
   <elementGuidId>90700c66-9d10-4608-9bf5-41d8c9b28e7f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[contains(text(),'Estimated Gas Fee')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.css-3zi4i8</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9f29ee8c-2713-4f7c-a4d9-af565f0c15ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-3zi4i8</value>
      <webElementGuid>885cb290-1a6d-47a2-a99e-c35139433ea1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>QC1</value>
      <webElementGuid>1765574b-492e-490b-8024-f4113eb40054</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;css-50on1g&quot;]/div[@class=&quot;css-1vyctbq&quot;]/div[@class=&quot;css-25zip3&quot;]/div[@class=&quot;css-1ksbb1k&quot;]/div[@class=&quot;css-18s4k7b&quot;]/div[@class=&quot;css-kodu7a&quot;]/div[@class=&quot;css-mdiws3&quot;]/div[@class=&quot;css-jzk2rw&quot;]/div[@class=&quot;css-wunri&quot;]/div[@class=&quot;css-15q091u&quot;]/div[@class=&quot;css-0&quot;]/div[@class=&quot;css-138ob9d&quot;]/div[@class=&quot;css-3zi4i8&quot;]</value>
      <webElementGuid>d9ecd063-a131-4bdd-a137-a4bd8a7ac4d6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[4]/div/div/div/div/div/div/div[3]/div[2]/div/div/div[2]</value>
      <webElementGuid>5ce332fb-f2c3-4fcc-8b1c-5db9eea38581</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tokens'])[1]/following::div[1]</value>
      <webElementGuid>67b95e9b-d9b8-4ce8-8062-d9890ea9c60f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Send'])[1]/following::div[5]</value>
      <webElementGuid>225295cb-fed0-4a4c-b465-efdd69b94f6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Amount'])[1]/preceding::div[1]</value>
      <webElementGuid>725e92c4-940d-4344-bed0-1c870542f837</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Estimated Gas Fee'])[1]/preceding::div[4]</value>
      <webElementGuid>488387aa-cbef-4610-9471-b191e674f356</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='QC1']/parent::*</value>
      <webElementGuid>99943bb6-e3b0-400d-a9d6-bbf02992cc53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]</value>
      <webElementGuid>7bd0936f-d2c8-4a29-b7e2-0dbaaa023bc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'QC1' or . = 'QC1')]</value>
      <webElementGuid>6b8d1a3f-0ac1-4ec2-99b6-c69b3a5391eb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
