<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Send ToToDoneAddress BookView AllRecent_66511d</name>
   <tag></tag>
   <elementGuidId>8e69a108-d756-4477-911b-7ebefa801345</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div[4]/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.css-1ksbb1k</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>56d680c4-bcba-49c4-914c-f11a1a2a44ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-1ksbb1k</value>
      <webElementGuid>ae18dcea-9536-4215-8419-dbf55a01941a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Send ToToDoneAddress BookView AllRecent Recipientmanhtt0x23f90e..b9fd4acf6c9CancelNext</value>
      <webElementGuid>7d240219-a849-4c12-b997-4bb868bf769a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;css-50on1g&quot;]/div[@class=&quot;css-1vyctbq&quot;]/div[@class=&quot;css-25zip3&quot;]/div[@class=&quot;css-1ksbb1k&quot;]</value>
      <webElementGuid>b3d76cb4-589e-4ea4-8a91-334e78259b52</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[4]/div/div</value>
      <webElementGuid>c99c4037-5663-451f-af13-eb44b71d44cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Setting'])[2]/following::div[3]</value>
      <webElementGuid>50e901f7-d5d6-4b34-b15f-370235196a99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Discovery'])[1]/following::div[8]</value>
      <webElementGuid>d81fc2b3-5c7f-4a11-9937-648b2e052580</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div</value>
      <webElementGuid>aa0743fe-2a59-4a09-9c27-31066a1270e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Send ToToDoneAddress BookView AllRecent Recipientmanhtt0x23f90e..b9fd4acf6c9CancelNext' or . = 'Send ToToDoneAddress BookView AllRecent Recipientmanhtt0x23f90e..b9fd4acf6c9CancelNext')]</value>
      <webElementGuid>15c6ba74-8f23-43c3-bb45-745d74fcf15a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
