<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_total_paid</name>
   <tag></tag>
   <elementGuidId>53847c67-001b-48f8-865e-b859b7d56dc1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[contains(text(),'Total Paid')]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>27b2ac65-bc99-43fe-bf56-cc2d967b7bdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-3zi4i8</value>
      <webElementGuid>685f6dbc-2bc9-4c83-99b5-8548c9b0e321</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>0.10  QC1</value>
      <webElementGuid>00f203d1-dc60-4e54-bc9f-ea4faff17665</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;css-50on1g&quot;]/div[@class=&quot;css-1vyctbq&quot;]/div[@class=&quot;css-25zip3&quot;]/div[@class=&quot;css-1ksbb1k&quot;]/div[@class=&quot;css-18s4k7b&quot;]/div[@class=&quot;css-kodu7a&quot;]/div[@class=&quot;css-mdiws3&quot;]/div[@class=&quot;css-jzk2rw&quot;]/div[@class=&quot;css-wunri&quot;]/div[@class=&quot;css-15q091u&quot;]/div[@class=&quot;css-0&quot;]/div[@class=&quot;css-138ob9d&quot;]/div[@class=&quot;css-3zi4i8&quot;]</value>
      <webElementGuid>f79d1974-953a-44d6-8922-f0dc5285cbbe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[4]/div/div/div/div/div/div/div[3]/div[2]/div/div[2]/div[2]</value>
      <webElementGuid>68936a0b-b934-4a34-b18f-4e0edfc9f1bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Amount'])[1]/following::div[1]</value>
      <webElementGuid>14195783-d6b5-44e1-83ce-ab9da2619740</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='QC1'])[1]/following::div[3]</value>
      <webElementGuid>9d2ff24a-e9df-442a-b518-99564cc70115</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Estimated Gas Fee'])[1]/preceding::div[1]</value>
      <webElementGuid>3faa457b-12fd-4008-be5d-2d6274f503e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total Paid'])[1]/preceding::div[4]</value>
      <webElementGuid>b5f5d89c-e03a-463c-b8cc-ff01980444b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='0.10']/parent::*</value>
      <webElementGuid>b612c5ed-ba28-4624-88e8-65a012e3d4bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div[2]</value>
      <webElementGuid>3d0c5dd5-bf4e-4669-8fb7-08a956635da0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '0.10  QC1' or . = '0.10  QC1')]</value>
      <webElementGuid>254c121b-12d8-4121-891f-385ef60439f8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
