<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Next_chakra-input css-z0go6q</name>
   <tag></tag>
   <elementGuidId>02a40b7b-abb4-4349-9427-7b05c6505fdc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='m']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.chakra-input.css-z0go6q</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7a3def2f-1cad-4b2f-a397-cbd33eca0346</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-input css-z0go6q</value>
      <webElementGuid>4b77e207-072f-4482-8288-ab8b711f09b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>m</value>
      <webElementGuid>e3939e55-c400-4d30-a369-f4531f562e52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;chakra-modal--body-:r3e:&quot;)/div[@class=&quot;css-j7qwjs&quot;]/div[@class=&quot;css-1kk651g&quot;]/div[@class=&quot;chakra-input__group css-1we85zz&quot;]/input[@class=&quot;chakra-input css-z0go6q&quot;]</value>
      <webElementGuid>a9642240-4319-483f-b9e2-122d70002327</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='m']</value>
      <webElementGuid>485b571d-06c9-48f2-9f22-32ea52118c2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='chakra-modal--body-:r3e:']/div/div[2]/div/input</value>
      <webElementGuid>4d8af706-68a7-4215-acb5-812e1ef04eaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>c801433c-6df0-4b1a-bdc4-ae7884ccc2cc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
