<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Setting_username_input</name>
   <tag></tag>
   <elementGuidId>3194e6cd-baad-4990-8598-eef743083152</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='username_input']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#username_input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>59861bb5-ce94-46f2-8e2b-62e37fe3d712</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Type username</value>
      <webElementGuid>95f99bce-d954-4e47-b1dc-b0e44c004d3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>username_input</value>
      <webElementGuid>4d4cb44d-e212-4a6e-b2ca-5cbc2844f532</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-input css-1hljxi7</value>
      <webElementGuid>19d09162-8336-4c61-8643-53dc2a9a4955</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;username_input&quot;)</value>
      <webElementGuid>3d6b73bf-4138-4ce2-b14a-dc74ac2cd289</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='username_input']</value>
      <webElementGuid>f67f7d89-6e25-4339-ab47-6a6f829a9a21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[4]/div/div/div/div/div/div/div/div/div/div/input</value>
      <webElementGuid>e7d68e57-faa8-44ef-a78c-f3772d7fe23a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>a674ea85-54f3-4a86-abdc-46cfc8665d99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Type username' and @id = 'username_input']</value>
      <webElementGuid>1bb28c85-2f07-4d14-b7d4-126eef0ed534</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
