<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Language-selection</name>
   <tag></tag>
   <elementGuidId>d277efd9-2fec-4b36-8db8-9a0f3c932cb1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.mkp-style-yuizo0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='menu-list-:r4:-menuitem-:r6:']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'English' or . = 'English')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>19b528a6-59c4-4d9b-a33e-fcacd52c407a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mkp-style-yuizo0</value>
      <webElementGuid>931dc11e-45f6-4bde-a660-1083da949471</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>English</value>
      <webElementGuid>32a20e86-9872-4ec5-a67d-1a21c209859a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-list-:r4:-menuitem-:r6:&quot;)/div[@class=&quot;mkp-style-yuizo0&quot;]</value>
      <webElementGuid>c8a3adff-77c5-4691-b7c4-59d93e334c0b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='menu-list-:r4:-menuitem-:r6:']/div[2]</value>
      <webElementGuid>4fc4585a-453f-4861-98c4-a315b64c8a5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Explore'])[1]/following::div[10]</value>
      <webElementGuid>489a7154-8694-40c9-a024-e287bad46549</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wallet'])[1]/preceding::div[7]</value>
      <webElementGuid>0ce7906e-4a22-4b55-8803-d4fa1adba2a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='English']/parent::*</value>
      <webElementGuid>20266036-7353-43bc-82e4-71e94f876747</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[3]/div/div/div/div/div[2]</value>
      <webElementGuid>bb5f0cf0-e508-438f-a6da-e5d0269ef443</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'English' or . = 'English')]</value>
      <webElementGuid>55427f54-f77a-4741-b07b-8f5123d567e3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
