<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Sell</name>
   <tag></tag>
   <elementGuidId>2e3bb125-2a79-44a5-9a8a-db134a71f6e7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'button' and @id = 'nft-card-place-bid-button-88' and (text() = 'Sell' or . = 'Sell')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[starts-with(@id, 'nft-card-place-bid-button') and text()='Sell']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#nft-card-place-bid-button-88</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5058a104-ce4a-4b9c-ba81-b50191a28d7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>efc56b7b-1e3f-4a28-a535-bf506d742a3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-button mkp-style-1nxou7-CTA</value>
      <webElementGuid>ef3030b4-bf78-4529-a46c-6d1ceaecc72e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nft-card-place-bid-button-88</value>
      <webElementGuid>555ed6d5-f764-4183-a5b9-1671bb8971e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sell</value>
      <webElementGuid>0d8cf696-3da8-44d9-9dcf-9b820df88537</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nft-card-place-bid-button-88&quot;)</value>
      <webElementGuid>5aeb0ab2-a4d9-459d-b59e-9abd98bbaf4a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='nft-card-place-bid-button-88']</value>
      <webElementGuid>c58d8978-432b-4f47-a314-50e1cb07cf34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tabs-:r85:--tabpanel-1']/div/div/div/div/div/div/div/div/div[2]/div[2]/div[2]/div/button</value>
      <webElementGuid>5ec163ce-97d5-41ab-9920-153e8e520bd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Price'])[1]/following::button[1]</value>
      <webElementGuid>20700897-4142-487b-879e-fa36523030d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Not For Sale'])[3]/preceding::button[1]</value>
      <webElementGuid>cdb35e7f-9cba-4cec-9f9c-e66197959060</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='In Wallet'])[3]/preceding::button[1]</value>
      <webElementGuid>1c7d6008-38d2-497b-bb53-debad30ff462</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sell']/parent::*</value>
      <webElementGuid>b05aee19-3db1-45ef-a9ec-c30a7f13243f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/button</value>
      <webElementGuid>5b6c66d9-3387-40e1-8ef7-988ee2a14abf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'nft-card-place-bid-button-88' and (text() = 'Sell' or . = 'Sell')]</value>
      <webElementGuid>cad063bb-2360-441f-8da3-26d93adeb578</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
