<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Sell</name>
   <tag></tag>
   <elementGuidId>2e3bb125-2a79-44a5-9a8a-db134a71f6e7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[starts-with(@id, 'nft-card-place-bid-button')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#nft-card-place-bid-button-88</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'button' and @id = 'nft-card-place-bid-button-88' and (text() = 'Sell' or . = 'Sell')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>18f57a50-5b10-490d-ba3e-41740685200a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>04990904-8716-4f5f-884a-f99e79779039</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-button mkp-style-1nxou7-CTA</value>
      <webElementGuid>72ca430c-29ba-4e79-91ec-5ceadcd9a90d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nft-card-place-bid-button-88</value>
      <webElementGuid>257a1497-58f4-42d0-bb51-6542aa7a3e37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sell</value>
      <webElementGuid>4e3a4e44-9e7e-43ae-aa2b-2e7fec1d34b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nft-card-place-bid-button-88&quot;)</value>
      <webElementGuid>99eace7c-c086-4205-bf99-346f7e058058</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='nft-card-place-bid-button-88']</value>
      <webElementGuid>c72a0653-007e-47af-860c-d4940e3318b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tabs-:r85:--tabpanel-1']/div/div/div/div/div/div/div/div/div[2]/div[2]/div[2]/div/button</value>
      <webElementGuid>96a30f55-7c40-4c2b-bc5c-ddc5b3878ac9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Price'])[1]/following::button[1]</value>
      <webElementGuid>77ca1541-d489-445a-8796-c653cec08f82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Not For Sale'])[3]/preceding::button[1]</value>
      <webElementGuid>7a184763-45f8-416c-bfd7-9b8a1a6f3c95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='In Wallet'])[3]/preceding::button[1]</value>
      <webElementGuid>0f57f2f2-2681-413f-893c-3178e96db5a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sell']/parent::*</value>
      <webElementGuid>abfae0c8-bb7d-42d7-b8ec-371de6834c61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/button</value>
      <webElementGuid>cdc988d3-3717-4ed7-b788-d902d605e675</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'nft-card-place-bid-button-88' and (text() = 'Sell' or . = 'Sell')]</value>
      <webElementGuid>b61447b9-fe7e-4af9-9ced-0b685e517b76</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
