<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_My Profile</name>
   <tag></tag>
   <elementGuidId>df2b2d33-a5ea-4ef8-959e-1c1a972623c0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.mkp-style-tk1yz</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[contains(text(),'My Profile')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8b2cd001-ebc4-4d61-a80b-ba2b2356f78b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mkp-style-tk1yz</value>
      <webElementGuid>5cc2ff5d-1d20-45d4-b804-94d3f62b51cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>My Profile</value>
      <webElementGuid>71ae88d2-baf9-4223-83db-ef0f0d73f417</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;popover-body-:r2:&quot;)/div[@class=&quot;mkp-style-zwiamn&quot;]/div[@class=&quot;mkp-style-wjsf6v&quot;]/button[@class=&quot;mkp-style-1e9tkau&quot;]/div[@class=&quot;mkp-style-tk1yz&quot;]</value>
      <webElementGuid>e2a8606e-cc19-40c2-8d7a-120a9df9aabb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='popover-body-:r2:']/div/div[2]/button/div</value>
      <webElementGuid>ad6ddce6-d3ed-4901-8ab9-b9fa98bc23ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Explore'])[1]/following::div[15]</value>
      <webElementGuid>63bb8ab0-63d4-490c-8853-ab3dc957adc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Settings'])[1]/preceding::div[1]</value>
      <webElementGuid>2895e6bb-678e-4c5b-a635-dec2f43972b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log out'])[1]/preceding::div[2]</value>
      <webElementGuid>a2869405-c575-4483-abab-5ba81615eeaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='My Profile']/parent::*</value>
      <webElementGuid>2416a68c-d2d4-4967-a55c-a65c050fe983</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button/div</value>
      <webElementGuid>fe702798-b79b-4b32-9872-8a5e7d764bef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'My Profile' or . = 'My Profile')]</value>
      <webElementGuid>a9122e67-c77a-4f42-a3d4-4fd7749c05f5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
