<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Owned</name>
   <tag></tag>
   <elementGuidId>e10d40c4-3485-407a-b383-af75019cf833</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tab-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[text()='Owned']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>87ca278e-330f-4172-89a7-86f76258bc48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tab-1</value>
      <webElementGuid>27784ab7-97b1-45bc-88e9-ddb17f793f6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mkp-style-0</value>
      <webElementGuid>3402df9b-7bac-4119-a721-bd553ffb0c89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Owned</value>
      <webElementGuid>411f6802-4265-46dc-b17c-1a7e9156712a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tab-1&quot;)</value>
      <webElementGuid>c07ef441-ee67-4123-817c-69dd7b86757c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='tab-1']</value>
      <webElementGuid>61b5aa98-a33e-47f2-b352-923ca2b824bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='tabs-:r85:--tab-1']/div</value>
      <webElementGuid>4eb85fb9-cb5e-4732-ab9d-86db3322acc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='On Market'])[1]/following::div[1]</value>
      <webElementGuid>c69b19ae-41d9-4478-bfc0-0fc7a2522a6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='A2E5c5..34490ca0'])[1]/following::div[8]</value>
      <webElementGuid>f400a153-f448-4f26-a76b-c512aa14dab6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bids'])[1]/preceding::div[1]</value>
      <webElementGuid>382ed67a-6893-46c6-881b-20cf55aba043</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Offers'])[1]/preceding::div[2]</value>
      <webElementGuid>5b7bed2c-16a3-4edd-bece-c688952c6f60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Owned']/parent::*</value>
      <webElementGuid>0ea9482b-1a1a-4745-8d3a-fd658f38807f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]/div</value>
      <webElementGuid>9e147b5f-16e9-4835-8385-4a87810dd8bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'tab-1' and (text() = 'Owned' or . = 'Owned')]</value>
      <webElementGuid>7b94eaa7-9f76-4fbd-80f9-88f54090bdcd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
