<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_header_profile_avatar</name>
   <tag></tag>
   <elementGuidId>0bc3670f-9af4-49a1-b004-ce494a3e7cea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;0x23A6AF&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='header-profile-avatar']/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>a7c45040-44b9-4915-bba9-65690365f001</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>0x23A6AF</value>
      <webElementGuid>0fd3eed0-bec9-4f3f-b0e4-b4cf3ad86e9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://ipfs.yoverse.io/ipfs/QmbzNHBR4xLGnKz5gBG6tbgW3YYBPUehQ2CUaQQD2APUGn</value>
      <webElementGuid>53c4e6d6-b388-44f9-bea5-51f2c51cdad9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>b9daf620-10b6-421f-b089-0c2247205a10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nimg</name>
      <type>Main</type>
      <value>fill</value>
      <webElementGuid>d10d5192-adf7-4e24-a77e-43aaa7a11569</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>8042ec9b-361d-4a41-adba-5de6cf5319fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header-profile-avatar&quot;)/div[@class=&quot;mkp-style-1br6nv8&quot;]/img[1]</value>
      <webElementGuid>7b7be763-c14e-4e5e-9f0e-bbb734a1d060</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='header-profile-avatar']/div/img</value>
      <webElementGuid>c0bb7b48-8695-4116-91ee-f89630d7de8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='0x23A6AF']</value>
      <webElementGuid>432e0811-a395-4393-b0de-7df44446f662</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/div/div/img</value>
      <webElementGuid>6f3f607f-0f1b-40b5-9263-6335065f52c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = '0x23A6AF' and @src = 'https://ipfs.yoverse.io/ipfs/QmbzNHBR4xLGnKz5gBG6tbgW3YYBPUehQ2CUaQQD2APUGn']</value>
      <webElementGuid>9115cc61-4bc1-4353-bd6b-56a9a001d40a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
