<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_fixed-price-amount</name>
   <tag></tag>
   <elementGuidId>96f4fec2-a13e-4381-8848-50f527563629</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='fixed-price-amount']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#fixed-price-amount</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4c4e168b-78d7-4c28-ac32-a54e0a0ba1a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>amount</value>
      <webElementGuid>fc2274a4-a3d5-4fdb-b139-0264b093df47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>18</value>
      <webElementGuid>b1478b91-4ffd-4726-93b5-d44508bd05c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fixed-price-amount</value>
      <webElementGuid>57f5e3ce-db64-4ac6-8d6c-f3902a8b2d4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-input mkp-style-1rkkcc7</value>
      <webElementGuid>fa2d21c2-053f-4d6f-bc6c-0c3ef3a25aaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fixed-price-amount&quot;)</value>
      <webElementGuid>3b2eeff0-db14-4c58-a9d6-f43ad2ea3a80</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='fixed-price-amount']</value>
      <webElementGuid>c1765f7b-19ac-4ed5-8160-2f0cd557805c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div/div/div[3]/div/div/div/div/div/div[2]/div[2]/div/div[2]/div[2]/div[2]/div/div/div/input</value>
      <webElementGuid>620295a8-b117-4273-a41f-4e48414f4b57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/input</value>
      <webElementGuid>56062e51-aca5-40fd-a04d-7720fda7dc7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'amount' and @id = 'fixed-price-amount']</value>
      <webElementGuid>674d8aeb-7aa7-4129-95a2-7e5053600825</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
