<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Private_Listing</name>
   <tag></tag>
   <elementGuidId>56b79f91-0fc9-4df1-82a3-9c6e6db3b7da</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.chakra-switch__thumb.mkp-style-7roig</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[contains(text(),'Private Listing')]/parent::div[starts-with(@class,'mkp-style')]/parent::div[starts-with(@class,'mkp-style')]/div/label/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c9ab6657-e59d-438f-8a53-719e2789397d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-switch__thumb mkp-style-7roig</value>
      <webElementGuid>a69e6c73-f542-4d2a-aa0b-f66f57e319e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[@class=&quot;__variable_9c9965 font-sans&quot;]/div[@class=&quot;mkp-style-0&quot;]/div[@class=&quot;mkp-style-1gaga0y&quot;]/div[@class=&quot;mkp-style-i9gxme&quot;]/div[@class=&quot;mkp-style-vooagt&quot;]/div[@class=&quot;mkp-style-6s1c6m&quot;]/div[@class=&quot;mkp-style-1r91zvi&quot;]/div[@class=&quot;chakra-stack mkp-style-lhu4x5&quot;]/div[@class=&quot;mkp-style-3yrk1f&quot;]/div[@class=&quot;mkp-style-anke3t&quot;]/div[@class=&quot;mkp-style-5u84wp&quot;]/div[@class=&quot;mkp-style-1dgpvj2&quot;]/div[@class=&quot;mkp-style-1o1h0be&quot;]/div[@class=&quot;mkp-style-1lekzkb&quot;]/label[@class=&quot;chakra-switch mkp-style-pc22x1&quot;]/span[@class=&quot;chakra-switch__track mkp-style-p27qcy&quot;]/span[@class=&quot;chakra-switch__thumb mkp-style-7roig&quot;]</value>
      <webElementGuid>b1b75bd0-bc86-4de5-a571-4981d1df40ab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div/div/div[3]/div/div/div/div/div/div[2]/div[2]/div/div[3]/div/label/span/span</value>
      <webElementGuid>50789981-3d0a-4b7d-99aa-a0c6ac8f736b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span</value>
      <webElementGuid>f6c09a1d-4df7-47c0-a963-d37023a854aa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
