<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_TWD</name>
   <tag></tag>
   <elementGuidId>77c12191-41da-4247-869b-7962f0ecf12e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[text()='TWD']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>926e65a7-9f9b-431d-a848-64ae3a86666c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>menu-list-:r4:-menuitem-:r6:</value>
      <webElementGuid>c9542aaa-1460-4457-b222-e9b9f482b710</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>db303c00-49ea-41aa-9c15-d90453a1286c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e30e831d-09f4-4614-849c-57b738c9b850</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-menu__menuitem mkp-style-1cg1ukq</value>
      <webElementGuid>c0be5c41-e31c-4777-9fa7-f4da9d029c3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-index</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>6796eff7-a7d8-46e2-80ce-07d2deff2b88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tiếng Việt</value>
      <webElementGuid>a73d9d07-78d7-45a8-98e8-9d4b62d945c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-list-:r4:-menuitem-:r6:&quot;)</value>
      <webElementGuid>35f2100c-fa0b-457a-9e72-73dbfb0c4a6f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='menu-list-:r4:-menuitem-:r6:']</value>
      <webElementGuid>5cd93d6a-cbbe-4aa9-947b-dcb4264daf10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='menu-list-:r4:']/div/div/div</value>
      <webElementGuid>77e6af3a-daa2-4c69-b6cc-1275af5ab4e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Khám phá'])[1]/following::div[8]</value>
      <webElementGuid>3b2c3991-3315-496d-9d71-42735f364dc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[3]/div/div/div/div</value>
      <webElementGuid>9861f604-b6ed-43b7-b1c8-e5253caf3131</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'menu-list-:r4:-menuitem-:r6:' and (text() = 'Tiếng Việt' or . = 'Tiếng Việt')]</value>
      <webElementGuid>ee9fefdb-84c3-4183-940e-be92a7068a7b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
