<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_CNY</name>
   <tag></tag>
   <elementGuidId>dde37d0b-aa56-468e-a538-113e347e27b6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.mkp-style-gnl226</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[text()='CNY']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>fb3c4025-9f06-4427-968b-be8875fb8227</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mkp-style-gnl226</value>
      <webElementGuid>d73bfc01-cef6-494b-98ab-8dc4b2c4298d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tiếng Việt</value>
      <webElementGuid>2741e23e-8a98-4c0c-b511-d2b346de3914</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tabs-:r2j:--tabpanel-0&quot;)/div[@class=&quot;mkp-style-8atqhb&quot;]/div[@class=&quot;mkp-style-xvo4vg&quot;]/div[@class=&quot;mkp-style-gnl226&quot;]</value>
      <webElementGuid>8de0b0d8-c795-46dc-917a-ed1e1da0d787</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tabs-:r2j:--tabpanel-0']/div/div/div[2]</value>
      <webElementGuid>9fb3a6b5-187e-4bcc-9176-189b72ad8081</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='English'])[2]/following::div[1]</value>
      <webElementGuid>03707471-fc8b-4991-915d-501d7d5ec298</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Choose your language and region'])[1]/following::div[10]</value>
      <webElementGuid>7ab2b2af-b37f-4e2e-9539-8ad87d82d142</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='繁體漢字'])[1]/preceding::div[7]</value>
      <webElementGuid>ad6d1184-9a49-48f7-8285-0355fafabf9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/div/div[3]/div/div/div/div[2]</value>
      <webElementGuid>75d74151-fa3a-4836-9e13-351075ffe7ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Tiếng Việt' or . = 'Tiếng Việt')]</value>
      <webElementGuid>cdf1c39f-2211-4dae-a8f9-74ffb4cadc2c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
