<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_62</name>
   <tag></tag>
   <elementGuidId>e2295e9e-b35e-4719-aaf1-5a7d6ba0fff4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.PcdZ8kUNXUSUHBUqTw3I.yN_n8hC6l0GZ5dHHJrtX > span.K_9lOyzfMyOzYBVic23K</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Thích bài viết'])[1]/following::span[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>fd127a48-a768-4358-baaa-33545ff4a37c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>K_9lOyzfMyOzYBVic23K</value>
      <webElementGuid>a99d9d2b-6c4e-431b-a456-8b54705b9a9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>62</value>
      <webElementGuid>9a0480f1-e570-48d5-ac45-2643f9b4a2cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;lunar-child contest-wrap&quot;]/main[@class=&quot;body container&quot;]/div[@class=&quot;contest-entries__container&quot;]/div[@class=&quot;contest-entries__interactive&quot;]/div[1]/div[@class=&quot;lazyload-wrapper&quot;]/div[@class=&quot;rOhzhvOe5EH8AFrzBVgh&quot;]/div[@class=&quot;JIVUv9eJ_aspOQorMdI4&quot;]/div[@class=&quot;TQI4j7cSKJZzBEgix2BD&quot;]/button[@class=&quot;PcdZ8kUNXUSUHBUqTw3I yN_n8hC6l0GZ5dHHJrtX&quot;]/span[@class=&quot;K_9lOyzfMyOzYBVic23K&quot;]</value>
      <webElementGuid>4731c116-de98-4ab8-a990-8d922fe746b5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thích bài viết'])[1]/following::span[4]</value>
      <webElementGuid>287e22dc-0a5d-44e6-af75-d45e1e56deb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='#2'])[1]/following::span[4]</value>
      <webElementGuid>94cf3630-7ab0-4adb-9eab-75a7fc8d7181</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bình luận'])[1]/preceding::span[2]</value>
      <webElementGuid>06ddcec4-dc0c-4dc0-a2f7-554ce9672f02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Chia sẻ'])[1]/preceding::span[3]</value>
      <webElementGuid>093f6d4c-54c0-4695-9d2f-0a2062731dd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='62']/parent::*</value>
      <webElementGuid>7d6e04f8-6f9c-4784-830f-d68ae08cb6b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[4]/span</value>
      <webElementGuid>3bb893ad-89b3-495e-8897-585778ac8400</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '62' or . = '62')]</value>
      <webElementGuid>e6dd6c0b-c379-451b-8f36-cdc00cbe0ab2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
