<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Login_Web3_Auth</name>
   <tag></tag>
   <elementGuidId>437865fb-e775-4eba-be21-05bb9e066c0f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.css-1v4xcoh > button.chakra-button.css-1wkivpk</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[contains(text(),'Connect Wallet')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0103f4cc-2499-4421-8292-e228200f70b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f6408150-13ad-4236-aae9-e9a033b818b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-button css-1wkivpk</value>
      <webElementGuid>322d870e-42ea-491a-bca0-e3daa3204779</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login Web3 Auth</value>
      <webElementGuid>a4cedb52-c067-4d34-b0d9-cfe5190181b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;css-1k8t7d9&quot;]/div[@class=&quot;css-tyuphr&quot;]/div[@class=&quot;css-1xyfuiw&quot;]/div[@class=&quot;css-sedd8i&quot;]/div[@class=&quot;css-1v4xcoh&quot;]/button[@class=&quot;chakra-button css-1wkivpk&quot;]</value>
      <webElementGuid>36896bd6-9678-453c-a6da-fb8ffb2b02ea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[4]</value>
      <webElementGuid>25cef30e-3b14-42fd-873e-cf0fdee40abf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div[2]/div[7]/div/button</value>
      <webElementGuid>b743042a-b681-40fe-87ed-a06361b63b29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Connect Wallet'])[1]/following::button[1]</value>
      <webElementGuid>ade8054e-f263-488e-9079-e33edeee0a1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SDK'])[1]/following::button[2]</value>
      <webElementGuid>77b1120c-229a-43e3-adbe-57a9e55b18f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Convert with near-zero gas fees'])[1]/preceding::button[1]</value>
      <webElementGuid>aeca0a35-1448-43da-95f6-20e1d02c8e36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/button</value>
      <webElementGuid>1edff743-ce1d-4bf1-9721-efcdabcf79dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Login Web3 Auth' or . = 'Login Web3 Auth')]</value>
      <webElementGuid>2b9e783a-cb24-4447-a699-59d25e98c062</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
