<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Buy TG</name>
   <tag></tag>
   <elementGuidId>d29a604b-101d-4fae-b646-614d4dc34153</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.chakra-button.css-2qrvc0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[15]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8b201204-dc3b-4ce1-a1e0-209747320f1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5be1a718-f493-4a39-b704-21a9fb13b4ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-button css-2qrvc0</value>
      <webElementGuid>9f464a5b-2113-4064-a811-c6c4017b9e25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Buy TG</value>
      <webElementGuid>2e0a0df4-ffdd-447b-851d-4efba9e38cb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;css-1k8t7d9&quot;]/div[@class=&quot;css-1mh151z&quot;]/div[@class=&quot;css-13lsbdg&quot;]/div[@class=&quot;css-3lm6u6&quot;]/div[@class=&quot;css-1ey50ed&quot;]/div[@class=&quot;css-84d43g&quot;]/div[@class=&quot;css-1bvalmt&quot;]/div[@class=&quot;css-1dbme2w&quot;]/button[@class=&quot;chakra-button css-2qrvc0&quot;]</value>
      <webElementGuid>0cc552d0-41b4-40c6-9be0-8cf02c62fa31</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[15]</value>
      <webElementGuid>3a1d6b62-ad9b-4be2-813d-58a9559f134a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div/div/div[2]/div[2]/div[2]/div/button</value>
      <webElementGuid>5e147efe-0596-41f4-9c02-533d2d4e106d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Avbl -'])[1]/following::button[1]</value>
      <webElementGuid>518f3ec6-a36c-4ee8-94dd-77ccd1f85911</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Order Confirmation'])[1]/following::button[1]</value>
      <webElementGuid>b8a83a7d-d030-404f-8294-3bced6d1490d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Avbl -'])[2]/preceding::button[1]</value>
      <webElementGuid>566b93a8-24f3-424d-9180-b0f5349dab7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Buy']/parent::*</value>
      <webElementGuid>d563eca4-e330-4bb4-90ab-810eb5a8cfdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[2]/div/button</value>
      <webElementGuid>fb13b725-1bd6-4221-bedc-1cc62ccc8745</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Buy TG' or . = 'Buy TG')]</value>
      <webElementGuid>4170c288-4065-4427-af13-a1df0b99fcb8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
