<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Create_a_collection</name>
   <tag></tag>
   <elementGuidId>2339245b-8226-4abc-95f8-3d4b0986bfd5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main']/div/div/section/div/header/span/div/div[2]/div/a</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//a[(text() = 'Create a collection' or . = 'Create a collection')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.sc-1f719d57-0.fKAlPV.sc-29427738-0.sc-788bb508-0.nFISH.bBXuZv</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6e661ca6-3261-4a67-b014-5e041f32ff86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-1f719d57-0 fKAlPV sc-29427738-0 sc-788bb508-0 nFISH bBXuZv</value>
      <webElementGuid>bc5cdadd-6422-4516-9056-611abaa712c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/collection/create</value>
      <webElementGuid>7bd342af-8232-4c5c-b083-2d49e0f323ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Create a collection</value>
      <webElementGuid>99b5be63-d681-48a1-be31-2bb9f8c2e535</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;sc-29427738-0 sc-630fc9ab-0 sc-99655001-0 jnYoOp jSPhMX kKyBpy&quot;]/div[@class=&quot;sc-e1c604fc-0 sNfQH&quot;]/section[@class=&quot;CollectionManager--main&quot;]/div[@class=&quot;sc-c14cb99b-0 jmMriM CollectionManager--container&quot;]/header[@class=&quot;sc-29427738-0 sc-630fc9ab-0 sc-99655001-0 dVNeWL jSPhMX kKyBpy&quot;]/span[@class=&quot;sc-29427738-0 sc-bdnxRM fgAoF jzBwsX&quot;]/div[@class=&quot;sc-61f0244f-0 hEkBrY&quot;]/div[@class=&quot;collectionManagerIndexHeader--buttons&quot;]/div[@class=&quot;sc-29427738-0 iihyIq&quot;]/a[@class=&quot;sc-1f719d57-0 fKAlPV sc-29427738-0 sc-788bb508-0 nFISH bBXuZv&quot;]</value>
      <webElementGuid>6a330eef-3c01-46d7-a8ed-0fffe5313d5c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main']/div/div/section/div/header/span/div/div[2]/div/a</value>
      <webElementGuid>ccdc288e-57fa-4f0e-b380-5ea574d44326</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Create a collection')]</value>
      <webElementGuid>818bf1ce-0f05-4940-ab0c-c55c85ae25b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='info'])[1]/following::a[1]</value>
      <webElementGuid>9b0f135d-3678-43ce-b72b-e7a59fc142cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='more_vert'])[1]/preceding::a[1]</value>
      <webElementGuid>dbf2ea41-4fba-4169-9b92-c10ec9992cb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='more_vert'])[2]/preceding::a[1]</value>
      <webElementGuid>e6be8224-6b0a-44a7-b101-1cc3935e3919</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Create a collection']/parent::*</value>
      <webElementGuid>eddf7b5e-1181-4fe2-90e3-d37cf0471ea1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/collection/create')]</value>
      <webElementGuid>3e384e58-eb97-41a0-b5d0-6ca7a3d3ebe3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a</value>
      <webElementGuid>862546c4-081c-4560-8882-5f5eb269ab24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/collection/create' and (text() = 'Create a collection' or . = 'Create a collection')]</value>
      <webElementGuid>dc02b2ba-cd83-4bba-9c0e-b65e8f06a046</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
