<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Create</name>
   <tag></tag>
   <elementGuidId>1fbf0351-c079-4c80-9818-7354b864b486</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.sc-29427738-0.sc-788bb508-0.iGtREG.bBXuZv</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2ae65895-82ab-4f2a-853f-88f625e0a4a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>29e5dc4f-0e55-481f-9801-e84deee44b92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-29427738-0 sc-788bb508-0 iGtREG bBXuZv</value>
      <webElementGuid>407a9ffb-4c22-4673-ba72-3c004df73d4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Create</value>
      <webElementGuid>5fc5e1e4-0115-4272-9d26-7cc8a70367aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;sc-29427738-0 sc-630fc9ab-0 sc-99655001-0 jnYoOp jSPhMX kKyBpy&quot;]/div[@class=&quot;sc-e1c604fc-0 sNfQH&quot;]/section[@class=&quot;CollectionManager--main&quot;]/div[@class=&quot;sc-c14cb99b-0 jmMriM CollectionManager--container CollectionManager--narrow-container&quot;]/form[@class=&quot;sc-29427738-0 sc-b37bf07-0 sc-604d6db-5 dVNeWL bbBWGr&quot;]/div[@class=&quot;sc-29427738-0 sc-630fc9ab-0 dVNeWL jSPhMX CollectionForm--submit&quot;]/button[@class=&quot;sc-29427738-0 sc-788bb508-0 iGtREG bBXuZv&quot;]</value>
      <webElementGuid>6850c470-b5f7-4845-a914-11dccec552a5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>3eb88dc7-6d3a-4b0d-9505-f4aafa23c18b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main']/div/div/section/div[2]/form/div[16]/button</value>
      <webElementGuid>0c2479eb-8f7b-4912-9ceb-5135dd8fceec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Turn on after all items revealed and attribute metadata is finalized.'])[1]/following::button[1]</value>
      <webElementGuid>1ee37ffe-7c0e-4191-9b25-b8d34d260469</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Learn more'])[3]/following::button[1]</value>
      <webElementGuid>dbf8c99b-c281-44fb-93ee-8d697137fe17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Create']/parent::*</value>
      <webElementGuid>f21053d9-852a-4889-bb35-94c1b4735e13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[16]/button</value>
      <webElementGuid>fe039c2f-a651-445c-9336-0b73976c0881</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'Create' or . = 'Create')]</value>
      <webElementGuid>da8f46df-cce0-44c6-b462-9330d9898ffa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
