<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>name_field</name>
   <tag></tag>
   <elementGuidId>eec2b1c7-cdf3-4c92-a01a-302fad559b48</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='name']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.sc-29427738-0.sc-630fc9ab-0.sc-99655001-0.sc-4422a702-0.sc-dada3b88-0.sc-3676ad3c-3.iibPCG.jSPhMX.kKyBpy.fYgjHJ.cmjqwQ.debpUl</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5c88f936-9f49-4f28-8ca7-2d31071d2f27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Select a banner image</value>
      <webElementGuid>6174648c-6a94-4f6d-bc68-c8140668969c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>200px</value>
      <webElementGuid>bb2e2bc4-cb22-44f7-807c-5371b377342a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>380d6d22-be5b-447a-83ea-844ae38833b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>677946d7-55f5-45a9-b8a1-4464aa8c6e5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>shape</name>
      <type>Main</type>
      <value>square</value>
      <webElementGuid>aecaae09-ac30-4d45-bb5e-e6ced9b672f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-29427738-0 sc-630fc9ab-0 sc-99655001-0 sc-4422a702-0 sc-dada3b88-0 sc-3676ad3c-3 iibPCG jSPhMX kKyBpy fYgjHJ cmjqwQ debpUl</value>
      <webElementGuid>1f5ec43d-2777-4185-b07a-0cc43405ef1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>b349b711-ace6-4ec0-9860-8f805cc8d12c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;sc-29427738-0 sc-630fc9ab-0 sc-99655001-0 jnYoOp jSPhMX kKyBpy&quot;]/div[@class=&quot;sc-e1c604fc-0 sNfQH&quot;]/section[@class=&quot;CollectionManager--main&quot;]/div[@class=&quot;sc-c14cb99b-0 jmMriM CollectionManager--container CollectionManager--narrow-container&quot;]/form[@class=&quot;sc-29427738-0 sc-b37bf07-0 sc-604d6db-5 dVNeWL bbBWGr&quot;]/div[@class=&quot;sc-29427738-0 sc-630fc9ab-0 sc-99655001-0 dVNeWL jSPhMX kKyBpy sc-b37bf07-1 vIGHJ&quot;]/div[@class=&quot;sc-29427738-0 sc-630fc9ab-0 dULEQL jSPhMX&quot;]/div[@class=&quot;sc-29427738-0 sc-630fc9ab-0 sc-99655001-0 sc-4422a702-0 sc-dada3b88-0 sc-3676ad3c-3 iibPCG jSPhMX kKyBpy fYgjHJ cmjqwQ debpUl&quot;]</value>
      <webElementGuid>9e827e44-2084-4e9d-84cc-ab03880a6bf6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main']/div/div/section/div[2]/form/div[3]/div/div[2]</value>
      <webElementGuid>a6d1c712-2830-4657-afc3-4bfc2ba04792</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Banner image'])[1]/following::div[1]</value>
      <webElementGuid>eea1369c-4ac0-4c66-931e-f3f0782c52d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='image'])[2]/following::div[5]</value>
      <webElementGuid>81f34139-8066-4714-a5c9-220bbfedea7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Name'])[1]/preceding::div[2]</value>
      <webElementGuid>9cfb4b77-7d01-4a44-b699-ba7c1038e522</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]</value>
      <webElementGuid>353c55df-2117-44c5-b33b-c76dba6331d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'image' or . = 'image')]</value>
      <webElementGuid>a03afd86-cf3a-4d9d-9f13-bb66819e07fa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
