<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Get your idea online_ns-3uu7l-e-9</name>
   <tag></tag>
   <elementGuidId>2ba31356-0c0d-4f19-aefc-e71d75a6748e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='banner-nologo']/div/div[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.ns-3uu7l-e-9</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>28b6afc7-da5e-4ad2-b577-29640c646888</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ns-3uu7l-e-9</value>
      <webElementGuid>4c959cd3-72a2-43a5-946f-95ddbc7b53ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;banner-nologo&quot;)/div[@class=&quot;ns-3uu7l-e-1 row-container canvas&quot;]/div[@class=&quot;ns-3uu7l-e-9&quot;]</value>
      <webElementGuid>51066a0f-516b-4d0a-bcae-8ccbc9b1c443</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='banner-nologo']/div/div[3]</value>
      <webElementGuid>e46a6763-0f2b-4013-b228-4b81c3a8080c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[3]</value>
      <webElementGuid>5bea696e-e71c-4f46-854d-c5027ce9ebcc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
