<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Sign in with AppleID</name>
   <tag></tag>
   <elementGuidId>904456ac-6bae-4e54-b011-c0bfb461442f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='account_name_text_field']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#account_name_text_field</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>772e2643-3e78-4e8d-a7b1-a58b8d446836</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>271a1683-88ff-4250-b98c-43771bcd256c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>account_name_text_field</value>
      <webElementGuid>97e2eef2-740d-4608-bdfd-5aa99ea0b71f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>can-field</name>
      <type>Main</type>
      <value>accountName</value>
      <webElementGuid>e45297fc-a0db-4411-9ffd-b9c231fa875c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>6393e34d-3606-41a1-a27a-deb1867d6968</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>c548929b-ac20-47cb-badd-10b56547d009</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>f31de9dd-ffc9-4b7c-8f84-fbff6a54fde7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>511b0a12-b0bc-4050-b418-6b90ba9ceece</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>f7547153-661c-4081-9616-aa60f613ab68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>bfb15e3e-46ea-45a8-831b-96e03a7ae0a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>($focus)</name>
      <type>Main</type>
      <value>appleIdFocusHandler()</value>
      <webElementGuid>453b6c51-75f6-493e-a8cb-35383f25bac1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>($keyup)</name>
      <type>Main</type>
      <value>appleIdKeyupHandler()</value>
      <webElementGuid>fa5c4cbe-4e5d-47be-9733-0230aeaec20e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>($blur)</name>
      <type>Main</type>
      <value>appleIdBlurHandler()</value>
      <webElementGuid>3e999a7c-e687-4413-971a-64ac3069cbc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>force-ltr form-textbox form-textbox-text </value>
      <webElementGuid>a1f451f7-1d55-43a6-8107-96c6ef022292</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>281be908-c7cc-4d05-894b-2b7598c919de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-focus-method</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>76d362c5-b26e-434b-b34f-9e4b46b0fe0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;account_name_text_field&quot;)</value>
      <webElementGuid>ba31e9d6-0924-41ba-8c8f-f38d860876ed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='account_name_text_field']</value>
      <webElementGuid>e89d5d5e-42df-4efe-891d-b5fa4caa9192</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sign_in_form']/div/div/div/div/div/input</value>
      <webElementGuid>55167227-d992-43ba-8577-64033ec3e73d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>a7f4b037-bfa8-4355-8637-4f5195391258</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'account_name_text_field']</value>
      <webElementGuid>d6082b48-d20b-4e89-8e5e-0753c61c8b69</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
