<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Offers</name>
   <tag></tag>
   <elementGuidId>9e241d95-208f-4028-9fbe-1aefabc11968</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tab-3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[text()='Offers']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>dc653402-35b1-4f02-8a7e-504fd393cb93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tab-3</value>
      <webElementGuid>eb1b8c71-aa30-4e26-8365-322d924dcd29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mkp-style-0</value>
      <webElementGuid>1593aa14-8b3f-40f3-94ab-514580732f63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Offers</value>
      <webElementGuid>0d228ef5-339e-49f4-bfbf-94d946ca7ae2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tab-3&quot;)</value>
      <webElementGuid>422ecb0b-b322-4b6e-8b7b-4075c8b4ee2a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='tab-3']</value>
      <webElementGuid>f6cdc2d9-5d78-45c5-8c68-b61c92ebde8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='tabs-:r48:--tab-3']/div</value>
      <webElementGuid>e1c3c267-4e70-483a-9dbd-9549574e50b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bids'])[1]/following::div[1]</value>
      <webElementGuid>8204a18c-39bb-4e4f-a533-6ac0a3b4ceda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Owned'])[1]/following::div[2]</value>
      <webElementGuid>d1c6f234-036b-4a4f-82d7-5a37a707b7e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Liked'])[1]/preceding::div[1]</value>
      <webElementGuid>fdfceead-cf84-434e-8e43-7ca03fb9c6e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Private'])[1]/preceding::div[2]</value>
      <webElementGuid>9ada6f92-0ef8-408e-a2a6-2cb1d5448571</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Offers']/parent::*</value>
      <webElementGuid>c5dd7ee0-c067-439a-b587-78c689365a89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[4]/div</value>
      <webElementGuid>8250674d-869a-4e27-ac69-ab9dc4694a27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'tab-3' and (text() = 'Offers' or . = 'Offers')]</value>
      <webElementGuid>a173eb50-ea58-4598-9d8d-337a95b4c154</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
