<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_My Profile</name>
   <tag></tag>
   <elementGuidId>7b23afcb-8ca2-4bfb-ba69-d01e138526a8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.mkp-style-tk1yz</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[contains(text(),'My Profile')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2b8cba2a-b115-4b47-93ba-c9c801e208c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mkp-style-tk1yz</value>
      <webElementGuid>c3b3ee8e-7cd9-4af2-ad68-e37d8e3c3ed2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>My Profile</value>
      <webElementGuid>cfd4adfd-4f47-4bb9-8a15-bd1032a1d885</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;popover-body-:r2:&quot;)/div[@class=&quot;mkp-style-zwiamn&quot;]/div[@class=&quot;mkp-style-wjsf6v&quot;]/button[@class=&quot;mkp-style-1e9tkau&quot;]/div[@class=&quot;mkp-style-tk1yz&quot;]</value>
      <webElementGuid>c5232b4d-8d2b-47e1-9996-ad5ea995ce02</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='popover-body-:r2:']/div/div[2]/button/div</value>
      <webElementGuid>3707a3dc-5ffe-4177-8e24-8148fa876ad5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Explore'])[1]/following::div[15]</value>
      <webElementGuid>175d336b-2022-4bbd-adad-09cd51f0f9f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Settings'])[1]/preceding::div[1]</value>
      <webElementGuid>31e01b2b-5397-44f0-afaa-af3fc995de00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log out'])[1]/preceding::div[2]</value>
      <webElementGuid>52a7c2b1-fe2a-479b-927b-f1506698abaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='My Profile']/parent::*</value>
      <webElementGuid>df338893-a247-491c-bcce-379d1e71bdd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button/div</value>
      <webElementGuid>85fd5b44-6e8b-4d39-964b-24b296a13e4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'My Profile' or . = 'My Profile')]</value>
      <webElementGuid>9da6ea20-b599-4b09-ba86-0136b33ce88a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
