<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Offer</name>
   <tag></tag>
   <elementGuidId>50d9aaa4-86e5-443c-9326-76f62c5f685f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.mkp-style-ag1a9c</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[text()='Offer']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>528f7d18-b77d-450d-a6aa-a2f73581e5f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mkp-style-ag1a9c</value>
      <webElementGuid>57a2fa32-e2ce-4338-b5ca-6f7eb918eead</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Offer</value>
      <webElementGuid>c99a9c0c-f2b0-43fa-b116-9a25d0ebe303</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;accordion-button-:r50:&quot;)/div[@class=&quot;mkp-style-ag1a9c&quot;]</value>
      <webElementGuid>162d97a3-7926-40df-9009-62e7bb9e83e7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='accordion-button-:r50:']/div</value>
      <webElementGuid>6507e526-2e3b-4b95-b941-01b787604428</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filters'])[1]/following::div[6]</value>
      <webElementGuid>d528206e-cd81-4d65-b18d-d37000765d42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Private'])[1]/following::div[11]</value>
      <webElementGuid>70d522d8-d3fb-40f3-bbde-7f31dd388370</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Made'])[1]/preceding::div[1]</value>
      <webElementGuid>63fab718-28d4-4292-b165-c86a21cf42b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Received'])[1]/preceding::div[2]</value>
      <webElementGuid>860a2e8b-3de5-42a2-80e1-e40ca55fd3b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Offer']/parent::*</value>
      <webElementGuid>78815012-98e8-4b95-96d2-f6c97191ac94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/button/div</value>
      <webElementGuid>944d3b1f-00f4-45dc-8a50-03d99e5cba45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Offer' or . = 'Offer')]</value>
      <webElementGuid>e1313686-1bae-42ba-a2c5-87f9c1d7c023</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
