<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Collection</name>
   <tag></tag>
   <elementGuidId>14ec4cbd-ccd0-42bd-88b0-7d80e00e8680</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[text()='Collection']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>22fbd9b6-39a8-4664-8396-bfa599b2dc16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mkp-style-ag1a9c</value>
      <webElementGuid>9183f3c7-3007-4a70-91aa-05e78339ed7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Collection</value>
      <webElementGuid>d2414037-510c-4fc9-b5cd-c8a3d73053a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;accordion-button-:r4c:&quot;)/div[@class=&quot;mkp-style-ag1a9c&quot;]</value>
      <webElementGuid>3f5392b8-987e-45df-8efd-8c564f06f805</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='accordion-button-:r4c:']/div</value>
      <webElementGuid>375f6bd5-7aa4-4cf1-8dbe-e9c71d32521b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='On Auction'])[1]/following::div[3]</value>
      <webElementGuid>78c89ef1-f68b-4845-b493-212ffbfe92a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='On Sale'])[1]/following::div[4]</value>
      <webElementGuid>52914bcf-eaf8-4355-a760-fc805f69f949</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='A Llamily Christmas'])[1]/preceding::div[1]</value>
      <webElementGuid>bedcc438-396d-4e65-8f9a-fcd881334b45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Collection 1155'])[1]/preceding::div[2]</value>
      <webElementGuid>3d8ef5d3-816e-4459-af12-b74d37baf317</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Collection']/parent::*</value>
      <webElementGuid>e1fa7e80-4cd1-4ae7-ac50-5362a7cf3c95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/button/div</value>
      <webElementGuid>b12e3b93-ee61-4a22-8ea0-5b7abeea8631</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Collection' or . = 'Collection')]</value>
      <webElementGuid>4501ca1b-6d9c-45c7-968f-f6d7999b7a8f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
