<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_user_address</name>
   <tag></tag>
   <elementGuidId>5371e647-ad49-449e-8416-157c663978c5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/div/div/div[3]/div/div/div/div[2]/div/div/div[2]/div/button/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.mkp-style-ik77zr</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = '23A6AF..37247e1E' or . = '23A6AF..37247e1E')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1b0c3bcc-7f0f-47d3-a626-0617af9c4141</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mkp-style-ik77zr</value>
      <webElementGuid>469fe357-420a-4427-988a-b1dfadeb9063</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>23A6AF..37247e1E</value>
      <webElementGuid>aef3dbd1-99a5-4c35-a14c-ffa291bc8ed0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[@class=&quot;__variable_9c9965 font-sans&quot;]/div[@class=&quot;mkp-style-0&quot;]/div[@class=&quot;mkp-style-1gaga0y&quot;]/div[@class=&quot;mkp-style-i9gxme&quot;]/div[@class=&quot;mkp-style-vooagt&quot;]/div[@class=&quot;mkp-style-6s1c6m&quot;]/div[@class=&quot;mkp-style-8aut8w&quot;]/div[@class=&quot;mkp-style-1hlq849&quot;]/div[@class=&quot;mkp-style-lv7k3g&quot;]/div[@class=&quot;mkp-style-azx95j&quot;]/div[@class=&quot;mkp-style-2vb0am&quot;]/div[@class=&quot;mkp-style-eihh2a&quot;]/button[@class=&quot;chakra-button mkp-style-tga90b-CTA&quot;]/div[@class=&quot;mkp-style-o146p0&quot;]/div[@class=&quot;mkp-style-ik77zr&quot;]</value>
      <webElementGuid>2f7494a7-332e-483d-a372-cd39536caa03</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div/div/div[3]/div/div/div/div[2]/div/div/div[2]/div/button/div/div</value>
      <webElementGuid>219a7c17-a892-4b83-a6f6-28744a0146cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Explore'])[1]/following::div[22]</value>
      <webElementGuid>310735c4-64ae-4159-90f5-dfe54bb47f92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='On Market'])[1]/preceding::div[5]</value>
      <webElementGuid>078c090f-86f5-4a0c-96d8-f7cc5b0a7327</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Owned'])[1]/preceding::div[6]</value>
      <webElementGuid>68b92ab7-4695-4974-8237-3396f4f99856</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='23A6AF..37247e1E']/parent::*</value>
      <webElementGuid>2258e735-a7bf-4d36-88ec-f69f8fabcbe6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/button/div/div</value>
      <webElementGuid>c939c0cb-fb70-4ec6-8bce-a87e3f67e1d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '23A6AF..37247e1E' or . = '23A6AF..37247e1E')]</value>
      <webElementGuid>bc4f8d99-19d8-49a7-aa19-1e282d10e698</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
