<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Bids</name>
   <tag></tag>
   <elementGuidId>7318e2fb-1456-44d1-a2fa-c157a44e37c9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tab-2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[text()='Bids']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>06229e3f-0b2c-470f-bd1b-bd43bb022e05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tab-2</value>
      <webElementGuid>74d4b54f-2b5c-4798-99a8-f35650067403</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mkp-style-0</value>
      <webElementGuid>1c4a6395-0b99-47a0-9a40-651c58468072</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Bids</value>
      <webElementGuid>ddf7cb29-62e5-4aca-a5b3-f6c09746b3fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tab-2&quot;)</value>
      <webElementGuid>eecbacce-1b0e-4ab0-b397-735b6a6457d6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='tab-2']</value>
      <webElementGuid>7d1232b3-9abf-4a3e-9c7f-5313fe478177</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='tabs-:r48:--tab-2']/div</value>
      <webElementGuid>4d3057ca-e9eb-4213-9fe3-00a46182624f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Owned'])[1]/following::div[1]</value>
      <webElementGuid>027cf402-342b-4865-8284-501c692d4eee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='On Market'])[1]/following::div[2]</value>
      <webElementGuid>46bdb104-c5e6-4116-afcb-5a0bbf7532e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Offers'])[1]/preceding::div[1]</value>
      <webElementGuid>3ffba840-66f5-4b72-be35-5b3838b0673c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Liked'])[1]/preceding::div[2]</value>
      <webElementGuid>32005a39-a34b-4364-977a-9b752f201bbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Bids']/parent::*</value>
      <webElementGuid>eee1de02-63fd-4e1a-9126-9c1ff3a44666</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[3]/div</value>
      <webElementGuid>5f75306c-3f24-41a0-9554-e90f139a97ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'tab-2' and (text() = 'Bids' or . = 'Bids')]</value>
      <webElementGuid>38f91832-5ec2-478e-a6b3-bc9bde53ac0e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
