<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Filters</name>
   <tag></tag>
   <elementGuidId>60ded8b1-0147-46d6-976f-753d12101f87</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.mkp-style-1p0tz8j</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[text()='Filters']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>90ecd596-1dfb-4833-9136-1dd80f4cb532</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mkp-style-1p0tz8j</value>
      <webElementGuid>674316d9-abdc-4192-9b77-c57561c29519</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Filters</value>
      <webElementGuid>03fde09f-6e6a-4994-923a-21489e44cb56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[@class=&quot;__variable_9c9965 font-sans&quot;]/div[@class=&quot;mkp-style-0&quot;]/div[@class=&quot;mkp-style-1gaga0y&quot;]/div[@class=&quot;mkp-style-i9gxme&quot;]/div[@class=&quot;mkp-style-vooagt&quot;]/div[@class=&quot;mkp-style-6s1c6m&quot;]/div[@class=&quot;mkp-style-8aut8w&quot;]/div[@class=&quot;mkp-style-1ns3q3q&quot;]/div[@class=&quot;chakra-tabs mkp-style-13o7eu2&quot;]/div[@class=&quot;mkp-style-1gkjcwr&quot;]/div[@class=&quot;mkp-style-0&quot;]/div[@class=&quot;chakra-stack mkp-style-hmuzod&quot;]/div[@class=&quot;mkp-style-1lsir5&quot;]/div[@class=&quot;mkp-style-1p0tz8j&quot;]</value>
      <webElementGuid>62e0447d-a109-4cc5-9be3-33f413882536</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div/div/div[3]/div/div/div/div[3]/div/div[2]/div/div/div/div</value>
      <webElementGuid>d2c0ced3-03eb-467f-a8a3-7a398fbe3551</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Private'])[1]/following::div[5]</value>
      <webElementGuid>6efafaa5-84a7-4b30-8c49-33d978de1215</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Liked'])[1]/following::div[6]</value>
      <webElementGuid>aadb93f9-84ef-4e12-9b7d-96b9c7df80be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sale Type'])[1]/preceding::div[2]</value>
      <webElementGuid>4d78a18c-24c1-4e52-a9bc-9268636d1405</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='On Sale'])[1]/preceding::div[4]</value>
      <webElementGuid>99835575-df7c-4523-8556-61a23123ae3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Filters']/parent::*</value>
      <webElementGuid>6bfd7974-7b1c-4b6e-9889-626ca437430d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div/div/div/div</value>
      <webElementGuid>3c67139e-a237-4357-a095-2a66455a0473</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Filters' or . = 'Filters')]</value>
      <webElementGuid>35b43b9b-1432-4c52-88f6-533654b8e9b9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
