<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Bid</name>
   <tag></tag>
   <elementGuidId>4b174cd5-116c-454d-8b67-7e9519e4f3f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.mkp-style-ag1a9c</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[text()='Bid']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f3d73b5a-aad5-48db-9499-5af61f91bb8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mkp-style-ag1a9c</value>
      <webElementGuid>cc16c61c-1a1c-499c-9476-68051f01a694</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Bid</value>
      <webElementGuid>7879999d-d177-4240-a8e9-323533627f63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;accordion-button-:r50:&quot;)/div[@class=&quot;mkp-style-ag1a9c&quot;]</value>
      <webElementGuid>5cc0a885-b426-445f-8a5d-f1c9c96d07e4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='accordion-button-:r50:']/div</value>
      <webElementGuid>43b44200-49d3-42b6-af20-adf1fcf1055a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filters'])[1]/following::div[6]</value>
      <webElementGuid>824b04aa-ffdb-4cb6-8ada-f73d2dbf05cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Private'])[1]/following::div[11]</value>
      <webElementGuid>9c697083-d69a-4e9e-8b7f-a2600fcc57c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Outbid'])[1]/preceding::div[1]</value>
      <webElementGuid>f7738b67-d12a-4695-b46c-de624ba78794</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Highest Bid'])[1]/preceding::div[2]</value>
      <webElementGuid>647ed047-3a0b-4cc8-8eb8-e23a1ac3a051</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Bid']/parent::*</value>
      <webElementGuid>8953abb0-f909-4d46-ad10-9f7d866055be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/button/div</value>
      <webElementGuid>91b98ad0-d661-49a0-a915-960ac5df17f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Bid' or . = 'Bid')]</value>
      <webElementGuid>a8a65573-981c-417b-b260-9cda506c4253</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
