<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Private</name>
   <tag></tag>
   <elementGuidId>7f5a733d-fdc8-42da-9337-9a150c67a860</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tab-5</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[text()='Private']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a84151e2-8d03-4e1e-8ab1-5ed446314ed2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tab-5</value>
      <webElementGuid>b1509682-f581-4dc8-843e-04c2dba83afb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mkp-style-0</value>
      <webElementGuid>0b0ca5e2-de29-4517-88e7-87ce14a8f0c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Private</value>
      <webElementGuid>0bd17005-7b48-4644-b6ae-0c9e5132e7cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tab-5&quot;)</value>
      <webElementGuid>b4e1ba3b-bb06-449b-8f62-15406a996f56</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='tab-5']</value>
      <webElementGuid>3d43c2a6-bc1d-45b5-92a4-71e308eafe40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='tabs-:r48:--tab-5']/div</value>
      <webElementGuid>c9c62d68-87dc-4b14-a297-2a8d7695887e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Liked'])[1]/following::div[1]</value>
      <webElementGuid>b763928d-ab44-4845-9e0c-2759a48c601f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Offers'])[1]/following::div[2]</value>
      <webElementGuid>383a94f3-6bf3-4714-a217-e4f60def51a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filters'])[1]/preceding::div[1]</value>
      <webElementGuid>c503257d-393b-4e11-9701-bf61f7eba66f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sale Type'])[1]/preceding::div[4]</value>
      <webElementGuid>4759f337-6b8a-4eec-81bf-19c1bd39afb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Private']/parent::*</value>
      <webElementGuid>f8f8f4d3-431f-42bc-8f04-01344ccb53a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[6]/div</value>
      <webElementGuid>e1ae55a0-88f5-46e3-808c-1fa61f0c136b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'tab-5' and (text() = 'Private' or . = 'Private')]</value>
      <webElementGuid>7d57948b-f390-4491-8c65-cf42ee3b5a14</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
