<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Liked</name>
   <tag></tag>
   <elementGuidId>e8e3d8fb-026a-4902-9b56-113faa9723ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tab-4</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[text()='Liked']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>16bf49f3-2a5d-4c53-8c7e-3d83ba855272</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tab-4</value>
      <webElementGuid>b5bfa7ad-44e6-481f-885a-805446121799</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mkp-style-0</value>
      <webElementGuid>fc3e21e6-30bf-472a-b022-2b3e899b46e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Liked</value>
      <webElementGuid>1f8d2c95-d25b-4f41-a6c7-844438a21c57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tab-4&quot;)</value>
      <webElementGuid>1c5cfeb0-9747-4e38-a229-2f0c14c212d5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='tab-4']</value>
      <webElementGuid>863af2db-bd10-4418-8dc0-bd038c723d41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='tabs-:r48:--tab-4']/div</value>
      <webElementGuid>d3479f00-6915-44e9-87e2-058949bff7ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Offers'])[1]/following::div[1]</value>
      <webElementGuid>9fe34004-22e3-44ca-9453-d51f4a392b35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bids'])[1]/following::div[2]</value>
      <webElementGuid>61a53be8-906c-415d-86ec-26b6ff0b138a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Private'])[1]/preceding::div[1]</value>
      <webElementGuid>b4794c88-6292-439b-8361-19bc395fca4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filters'])[1]/preceding::div[2]</value>
      <webElementGuid>26bb3072-d914-4618-9ff8-eb6564408deb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Liked']/parent::*</value>
      <webElementGuid>b8953c74-80f3-436f-96f0-46a6961e13d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[5]/div</value>
      <webElementGuid>44fc5482-5405-4b0b-b75a-3b0c7e9e9572</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'tab-4' and (text() = 'Liked' or . = 'Liked')]</value>
      <webElementGuid>b599b39d-7ac1-48e5-8cca-42301b405309</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
