<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Login_Web3_Auth</name>
   <tag></tag>
   <elementGuidId>72746ad4-caf8-4c22-859a-d2041a30a395</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.css-1v4xcoh > button.chakra-button.css-1wkivpk</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[contains(text(),'Connect Wallet')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4f47e957-894d-4500-892b-d19cced327f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>48b1327d-8322-4af1-bd18-aa6b848fbb39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-button css-1wkivpk</value>
      <webElementGuid>e3b91a65-794c-4df2-bd47-b31789cd9e15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login Web3 Auth</value>
      <webElementGuid>867b6876-204b-4071-ad6d-c5c10b65458c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;css-1k8t7d9&quot;]/div[@class=&quot;css-tyuphr&quot;]/div[@class=&quot;css-1xyfuiw&quot;]/div[@class=&quot;css-sedd8i&quot;]/div[@class=&quot;css-1v4xcoh&quot;]/button[@class=&quot;chakra-button css-1wkivpk&quot;]</value>
      <webElementGuid>2d4a894a-e0a4-4d38-8a88-86884c0c29e2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[4]</value>
      <webElementGuid>b6268b8f-7d6e-4f70-b44e-7113adda2beb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div[2]/div[7]/div/button</value>
      <webElementGuid>9007e859-3b49-46fe-a688-fe5b17e4af02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Connect Wallet'])[1]/following::button[1]</value>
      <webElementGuid>8541cb07-1ff2-42d9-8e36-8c9bedf2e755</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SDK'])[1]/following::button[2]</value>
      <webElementGuid>d7ab8c39-c7eb-4085-819f-1193f028e2a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Convert with near-zero gas fees'])[1]/preceding::button[1]</value>
      <webElementGuid>51d3a8a9-3588-42a8-a3a1-597cb00670f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/button</value>
      <webElementGuid>a0b536d0-0d05-4da3-83d3-10f65e291fd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Login Web3 Auth' or . = 'Login Web3 Auth')]</value>
      <webElementGuid>415963e1-a977-455d-bf0d-54724fc05257</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
