<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Settings</name>
   <tag></tag>
   <elementGuidId>e597ba17-fb9d-484c-8d63-d68bb1450d13</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[contains(text(),'Settings')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Settings' or . = 'Settings')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>02bdb4c1-03ac-4549-b398-195507e36b96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mkp-style-tk1yz</value>
      <webElementGuid>a895af41-7954-4536-86df-dbe61284dad0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Settings</value>
      <webElementGuid>acfc2f4b-7a74-4c92-8fb0-832345e91b37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;popover-body-:r2m:&quot;)/div[@class=&quot;mkp-style-zwiamn&quot;]/div[@class=&quot;mkp-style-wjsf6v&quot;]/button[@class=&quot;mkp-style-1e9tkau&quot;]/div[@class=&quot;mkp-style-tk1yz&quot;]</value>
      <webElementGuid>763b9452-48fc-4d66-a2ff-b597378c47a6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='popover-body-:r2m:']/div/div[2]/button[2]/div</value>
      <webElementGuid>5311ece7-372d-4c42-84cf-8a7994698483</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Profile'])[1]/following::div[1]</value>
      <webElementGuid>59a63bae-c175-4c21-aae7-39255b2fed42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Explore'])[1]/following::div[16]</value>
      <webElementGuid>34d8fa72-9dc1-4cec-8a7a-953524c66469</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log out'])[1]/preceding::div[1]</value>
      <webElementGuid>869a7230-8215-48af-9e07-487fa4d8723b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='STAR'])[1]/preceding::div[3]</value>
      <webElementGuid>b74d09ce-5396-46a4-bc10-a2b03863cb3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Settings']/parent::*</value>
      <webElementGuid>59a3d3c9-f07b-43b1-a3c4-df8d43da073c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]/div</value>
      <webElementGuid>2bad4763-d52b-4b4a-990c-7d6a48698aa4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Settings' or . = 'Settings')]</value>
      <webElementGuid>e311153f-b4be-4a4d-aa04-e6cfa754f170</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
