<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Save</name>
   <tag></tag>
   <elementGuidId>743426d1-cf9d-4e46-bbc5-ce3f2ab99946</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.mkp-style-o146p0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[contains(text(),'Save')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b6b5fb72-98e5-4374-8027-bada0c4e3711</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mkp-style-o146p0</value>
      <webElementGuid>21b16765-f9c2-4b9e-a324-877cfec5a3d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Save</value>
      <webElementGuid>3f213295-e74d-4e9a-becb-5425c7b919d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tabs-:r39:--tabpanel-0&quot;)/div[@class=&quot;mkp-style-j7qwjs&quot;]/div[@class=&quot;mkp-style-1ufmpwf&quot;]/div[@class=&quot;mkp-style-1jvopm1&quot;]/div[@class=&quot;chakra-stack mkp-style-tncdwt&quot;]/div[@class=&quot;mkp-style-1ki54i&quot;]/button[@class=&quot;chakra-button mkp-style-1tc3ogu-CTA&quot;]/div[@class=&quot;mkp-style-o146p0&quot;]</value>
      <webElementGuid>0dd8b4eb-1f85-4961-984b-7cd5db265da4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tabs-:r39:--tabpanel-0']/div[2]/div[2]/div/div/div[5]/button/div</value>
      <webElementGuid>1cda5729-b449-4c4c-b603-20d13ee1dffc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wallet address'])[1]/following::div[5]</value>
      <webElementGuid>c622fc5e-c447-4c97-a74a-ac0d40b0ee64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Personal site'])[1]/following::div[8]</value>
      <webElementGuid>bf6509f5-4a29-463d-97f3-5c1534dceb11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Profile Avatar'])[1]/preceding::div[1]</value>
      <webElementGuid>4df77de0-ca0f-40cc-9df8-e35e08cc4f95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Profile Cover'])[1]/preceding::div[4]</value>
      <webElementGuid>6e5d65ad-65d0-443b-9042-4af91a807e1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Save']/parent::*</value>
      <webElementGuid>11a80091-6468-4ee9-b1d5-f8a7e8c9f8a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/button/div</value>
      <webElementGuid>560a367e-3bed-4c8c-83d1-24bb0f560411</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Save' or . = 'Save')]</value>
      <webElementGuid>1af07d62-b27f-4c19-a9db-016fb69c22f1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
