<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_header_profile_avatar</name>
   <tag></tag>
   <elementGuidId>1a838c7f-1ebb-4d78-b98c-3ef76b051ca1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='header-profile-avatar']/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;0x23A6AF&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>8809f27c-b718-42a0-b720-aabd52493b17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>0x23A6AF</value>
      <webElementGuid>10c31c29-1f98-4c44-8cd4-fac02adcad07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://ipfs.yoverse.io/ipfs/QmbzNHBR4xLGnKz5gBG6tbgW3YYBPUehQ2CUaQQD2APUGn</value>
      <webElementGuid>f8da7f49-56c2-4565-aeff-2c8f00781a75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>a97ebd8a-64b1-47cc-b897-ec98562db860</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nimg</name>
      <type>Main</type>
      <value>fill</value>
      <webElementGuid>36bc5081-3cab-4e70-93ea-e9e3418bcb90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>8ccf116f-3dea-4393-8926-50080466de7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header-profile-avatar&quot;)/div[@class=&quot;mkp-style-1br6nv8&quot;]/img[1]</value>
      <webElementGuid>62e20a4c-a20e-4758-80df-15012a82dc21</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='header-profile-avatar']/div/img</value>
      <webElementGuid>9f558860-1f53-4e35-911d-63021ed92897</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='0x23A6AF']</value>
      <webElementGuid>d8dc390f-0e65-4197-b9fc-d5375393ebf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/div/div/img</value>
      <webElementGuid>01472583-39eb-4323-9ef5-d221044cf023</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = '0x23A6AF' and @src = 'https://ipfs.yoverse.io/ipfs/QmbzNHBR4xLGnKz5gBG6tbgW3YYBPUehQ2CUaQQD2APUGn']</value>
      <webElementGuid>32532b9f-1ca3-4d8b-8dc3-ff564629a1ce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
