<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg_apple</name>
   <tag></tag>
   <elementGuidId>29b42ba8-dec9-463d-becb-cfdfecf7ea3f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>svg</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[contains(text(),'Or continue with')]/parent::div/following-sibling::div/div[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>791b59d6-804b-4657-8834-17a29d08e96c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>52</value>
      <webElementGuid>c264baab-5cc3-4163-89d2-95340d71b335</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>52</value>
      <webElementGuid>3328570e-d0de-4bd7-b320-a2ed0357396d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 52 52</value>
      <webElementGuid>fbe4f49b-830a-48ce-8722-d2e5a0d10563</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>b19b7025-e47c-48bc-93f4-ee6a7f453319</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>4a69bc20-5133-4e20-a714-9b0a496f3511</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;css-1urx3od&quot;]/div[@class=&quot;chakra-container css-l9zmzb&quot;]/div[@class=&quot;css-10h1f7x&quot;]/div[@class=&quot;css-txdpd1&quot;]/div[@class=&quot;css-7byvoj&quot;]/div[@class=&quot;css-cvovcd&quot;]/div[@class=&quot;css-1u989rg&quot;]/form[1]/div[@class=&quot;css-1s10cg8&quot;]/div[@class=&quot;css-2bl54b&quot;]/div[@class=&quot;css-8y6dpg&quot;]/svg[1]</value>
      <webElementGuid>5f623d7f-b552-4a3d-b2f1-bd3e2a434168</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Or continue with'])[1]/following::*[name()='svg'][1]</value>
      <webElementGuid>7837a207-f040-4145-9c23-493add258849</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Continue'])[1]/following::*[name()='svg'][1]</value>
      <webElementGuid>eeb75c3c-495f-41b1-b06e-7e78874a3ae5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='By continuing, you agree to our'])[1]/preceding::*[name()='svg'][3]</value>
      <webElementGuid>ace679dc-0f2c-4660-b2b0-54d889b0e361</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terms of Service'])[1]/preceding::*[name()='svg'][3]</value>
      <webElementGuid>ef941f60-7dcd-4b27-ad31-dd54e8ebc525</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
