<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>text_Continue with below options</name>
   <tag></tag>
   <elementGuidId>ec1ed5b7-586d-4ec1-90eb-bdc7d08cd758</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div/div/div/div/div/div[2]/form/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.css-epkn46</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(contains(text(), 'Continue with below options to join the crypto world with an easy!') or contains(., 'Continue with below options to join the crypto world with an easy!'))]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>41ac329d-77c8-4214-b661-711f5cb03ab3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-epkn46</value>
      <webElementGuid>80c904dc-d807-428a-b0c0-310b0b0e5663</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Continue with below options to join the crypto world with an easy!</value>
      <webElementGuid>984d0bce-336a-4cca-8574-782e86470647</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;css-1urx3od&quot;]/div[@class=&quot;chakra-container css-l9zmzb&quot;]/div[@class=&quot;css-10h1f7x&quot;]/div[@class=&quot;css-txdpd1&quot;]/div[@class=&quot;css-7byvoj&quot;]/div[@class=&quot;css-cvovcd&quot;]/div[@class=&quot;css-1u989rg&quot;]/form[1]/div[@class=&quot;css-epkn46&quot;]</value>
      <webElementGuid>996bd388-f66d-4854-b375-4adbcb160900</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div/div/div/div/div[2]/form/div[2]</value>
      <webElementGuid>b31ea99f-4337-4b5d-8176-6f760749ee2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Welcome to Wallet'])[1]/following::div[1]</value>
      <webElementGuid>cc2173b5-a89d-4858-9102-d65916c35dc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Continue'])[1]/preceding::div[4]</value>
      <webElementGuid>bb67d470-4c6f-4ead-84d3-b6b10376c389</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Or continue with'])[1]/preceding::div[5]</value>
      <webElementGuid>0867c3ef-544c-4d1c-8a32-515ee988ab1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Continue with below options to join the crypto world with an easy!']/parent::*</value>
      <webElementGuid>591d68fc-1c07-4fe3-93bd-95e5f0f38b48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]</value>
      <webElementGuid>cd5dbf92-ca6a-4f94-ae9f-6707df7b4ba3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Continue with below options to join the crypto world with an easy!' or . = 'Continue with below options to join the crypto world with an easy!')]</value>
      <webElementGuid>9b79ece0-b682-4781-923b-c6824f505e99</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
