<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Explore</name>
   <tag></tag>
   <elementGuidId>04271b61-7fbe-4ca0-bca0-7fdf8e951d32</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[text()='Explore']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.css-krrhz0</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Explore' or . = 'Explore')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1f17bcd6-9140-4229-bef4-e9cde52f3419</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-krrhz0</value>
      <webElementGuid>b017fb41-02a9-42c4-a1d9-93a5d3b91d96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Explore</value>
      <webElementGuid>f7da45d6-52c1-4d2c-a6e5-a4ed37bc63cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;css-0&quot;]/div[@class=&quot;css-1gaga0y&quot;]/div[@class=&quot;css-1c9yncn&quot;]/div[@class=&quot;css-3ldsh6&quot;]/div[@class=&quot;css-wjv7v2&quot;]/div[@class=&quot;css-ocarbj&quot;]/div[@class=&quot;css-e3hmlp&quot;]/div[@class=&quot;css-krrhz0&quot;]</value>
      <webElementGuid>c31ed851-726c-4cc0-8d43-b82004e5e088</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div/div/div[3]/div/div/div</value>
      <webElementGuid>8d423d30-3e98-48a9-8ebd-b7c9476120f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Connect Wallet'])[1]/preceding::div[3]</value>
      <webElementGuid>9797e233-6982-4f02-bcfc-17bd5ab1550f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='For Collectors'])[1]/preceding::div[6]</value>
      <webElementGuid>abf06b9d-dcb6-44c1-9fa0-3cb89a928152</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Explore']/parent::*</value>
      <webElementGuid>7603a02a-4042-49c0-bee4-dd9e76447698</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div</value>
      <webElementGuid>1178e055-6647-45b0-b5bc-d94073d1e2e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Explore' or . = 'Explore')]</value>
      <webElementGuid>609a1f39-87c5-4387-b0a7-1f8c1bde983a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
