<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Filters</name>
   <tag></tag>
   <elementGuidId>43467c85-2cf6-476f-8391-49c9dacea888</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[text()='Filters']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.css-1p0tz8j</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Filters' or . = 'Filters')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e947d9b1-b280-41e8-ba7d-e312fc258a37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-1p0tz8j</value>
      <webElementGuid>794e7494-38e6-47d6-a984-2ce30037bbfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Filters</value>
      <webElementGuid>26ee618d-7c85-4d17-8fc9-43aed073e993</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tabs-:r2b:--tabpanel-1&quot;)/div[1]/div[@class=&quot;css-0&quot;]/div[@class=&quot;css-k008qs&quot;]/div[@class=&quot;chakra-stack css-1mcw2p8&quot;]/div[@class=&quot;css-1lsir5&quot;]/div[@class=&quot;css-1p0tz8j&quot;]</value>
      <webElementGuid>270c3ef6-ee27-4c8f-b742-c3a41ab993a7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tabs-:r2b:--tabpanel-1']/div/div/div/div/div/div</value>
      <webElementGuid>3bf5f877-0c02-4217-b58f-ef35c18eb7ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Collections'])[1]/following::div[9]</value>
      <webElementGuid>0f32ec2e-3a18-4a32-91c0-fbd2c0808684</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NFTs'])[1]/following::div[9]</value>
      <webElementGuid>0fdc0a57-e11c-478a-9124-4bed33b65286</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Category'])[1]/preceding::div[2]</value>
      <webElementGuid>5ab09f10-dc8a-4613-8a4f-48cd486b2498</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Names'])[1]/preceding::div[4]</value>
      <webElementGuid>5cea8bf0-9c4a-4a78-b92e-ff99fed26870</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Filters']/parent::*</value>
      <webElementGuid>2c683bd4-8ed4-4501-acd8-b7a3db7e2c93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[2]/div/div/div/div/div/div</value>
      <webElementGuid>fa5e9bf7-41f6-4d8e-982d-b191c98ba4eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Filters' or . = 'Filters')]</value>
      <webElementGuid>591d95dd-6770-44df-b5e8-bc289693f0fb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
