<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Continue_Submit</name>
   <tag></tag>
   <elementGuidId>23229434-e008-43cc-88cb-f047ec2a068f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.chakra-button.css-t2mvff</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'submit' and (text() = 'Continue' or . = 'Continue')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7a57aadf-e16d-4613-aa45-6b52815707f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>d9819006-76b6-4a4a-a46c-370df1699ba5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-button css-t2mvff</value>
      <webElementGuid>4fff6562-0f71-49a9-b9a9-759a0bc58d71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Continue</value>
      <webElementGuid>ee696d62-fd21-4e31-916b-8ff0c036988b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;css-1urx3od&quot;]/div[@class=&quot;chakra-container css-l9zmzb&quot;]/div[@class=&quot;css-10h1f7x&quot;]/div[@class=&quot;css-txdpd1&quot;]/div[@class=&quot;css-7byvoj&quot;]/div[@class=&quot;css-cvovcd&quot;]/div[@class=&quot;css-1u989rg&quot;]/form[1]/div[@class=&quot;css-fdxmw&quot;]/button[@class=&quot;chakra-button css-t2mvff&quot;]</value>
      <webElementGuid>a9e4b4a8-2e27-41d0-a5c6-d52f73d5bcea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>ac4ce8e6-19e2-4a1c-9ca3-2f7000a2be92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div/div/div/div/div[2]/form/div[3]/button</value>
      <webElementGuid>11b79522-aa2d-4a98-8870-224e3a7c5362</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Continue with below options to join the crypto world with an easy!'])[1]/following::button[1]</value>
      <webElementGuid>af28e324-0145-43bc-a4e3-315fa0fbfc43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Welcome to Wallet'])[1]/following::button[1]</value>
      <webElementGuid>3ff2c89c-9aab-415b-86d7-fc632d748d97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Or continue with'])[1]/preceding::button[1]</value>
      <webElementGuid>283428ba-8298-41b9-8975-a1bef11f8470</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='By continuing, you agree to our'])[1]/preceding::button[1]</value>
      <webElementGuid>cbc4f313-6d6e-4cf7-b51d-16fe7a2bbbbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Continue']/parent::*</value>
      <webElementGuid>b6692757-b591-47c8-8509-cf5ae248c617</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>af697e00-c12c-4c49-9851-59708e98cf57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'Continue' or . = 'Continue')]</value>
      <webElementGuid>39c76005-03e1-4a1f-bb41-0e2a668b49bf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
