<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_username</name>
   <tag></tag>
   <elementGuidId>ce568b7c-3c46-4b2a-a17d-f6043b1b949e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='username']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;username&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5c0c3415-3507-4618-bd5a-8bbbe16da973</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter your username</value>
      <webElementGuid>059d7bee-76d2-4d4d-9664-9d8c674f3ad6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>username</value>
      <webElementGuid>0a78747c-ed18-4b9d-8237-1bba8fa61f4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-input css-10nms28</value>
      <webElementGuid>f4be59c2-ce44-4fb1-8ae2-9956e99f7449</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;css-1urx3od&quot;]/div[@class=&quot;chakra-container css-l9zmzb&quot;]/div[@class=&quot;css-10h1f7x&quot;]/div[@class=&quot;css-txdpd1&quot;]/div[@class=&quot;css-7byvoj&quot;]/div[@class=&quot;css-cvovcd&quot;]/div[@class=&quot;css-1u989rg&quot;]/div[@class=&quot;css-0&quot;]/div[@class=&quot;css-0&quot;]/div[@class=&quot;css-fdxmw&quot;]/input[@class=&quot;chakra-input css-10nms28&quot;]</value>
      <webElementGuid>8e0fa8ea-4eec-4c3a-ab88-896d481b4473</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='username']</value>
      <webElementGuid>e401e0a0-f535-4560-a0d9-56fa4634cb6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div/div/div/div/div[2]/div/div/div[3]/input</value>
      <webElementGuid>e346fb2c-d1f0-485c-9193-38ad221db7ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>5491e44b-f578-4f74-9fd7-efcc6803c956</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Enter your username' and @name = 'username']</value>
      <webElementGuid>5811f7b8-1f4c-4a22-afe9-d884f823cd3d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
