<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Login_Web3_Auth</name>
   <tag></tag>
   <elementGuidId>5627b123-3114-493f-b1da-98edff5a940c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[contains(text(),'Connect Wallet')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.css-1v4xcoh > button.chakra-button.css-1wkivpk</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7239219e-bcbd-4aa9-91a4-037d86978366</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6f228ba3-6ea4-4192-b81f-248602964c35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-button css-1wkivpk</value>
      <webElementGuid>70625db2-44df-46f2-a758-9bd11ebd715a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login Web3 Auth</value>
      <webElementGuid>4997f816-abfb-4eaa-ac24-03086c279e5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;css-1k8t7d9&quot;]/div[@class=&quot;css-tyuphr&quot;]/div[@class=&quot;css-1xyfuiw&quot;]/div[@class=&quot;css-sedd8i&quot;]/div[@class=&quot;css-1v4xcoh&quot;]/button[@class=&quot;chakra-button css-1wkivpk&quot;]</value>
      <webElementGuid>2b8ef7da-c999-498d-a2f6-c72f8d6e57f6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[4]</value>
      <webElementGuid>ad1e84b0-e9fc-4f83-a355-4ef5c66536b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div[2]/div[7]/div/button</value>
      <webElementGuid>aca125df-5acf-460f-84b2-bde5efbb8c0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Connect Wallet'])[1]/following::button[1]</value>
      <webElementGuid>fedf6a8c-38a1-48f1-b8ea-03a6d912ef7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SDK'])[1]/following::button[2]</value>
      <webElementGuid>b152cc68-8925-4642-80e6-71654a32d96a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Convert with near-zero gas fees'])[1]/preceding::button[1]</value>
      <webElementGuid>ca81df41-33f0-4f7e-a6c9-a7a46d6b960a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/button</value>
      <webElementGuid>cd3f4040-4272-4712-a602-a29b89e4214d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Login Web3 Auth' or . = 'Login Web3 Auth')]</value>
      <webElementGuid>a8ff0049-d74d-413d-a289-6ae483fb3423</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
