<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Lets_me_Edit</name>
   <tag></tag>
   <elementGuidId>2da3be2d-ddfb-4d7c-9db8-754f352d1480</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'button' and (text() = 'Let’s me Edit' or . = 'Let’s me Edit')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[contains(text(),'Let’s me Edit')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.chakra-button.css-16tyxzg</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>af1d7ef1-f4f6-40f7-9149-9416cf860084</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>02092461-de4a-4976-bc8a-acbcc30800d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-button css-16tyxzg</value>
      <webElementGuid>1d08853d-8fb8-46bc-a76d-b60dc93025b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Let’s me Edit</value>
      <webElementGuid>313f4703-86dd-4bac-8d41-e2a4979687ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;chakra-modal-:R1b9f6:&quot;)/footer[@class=&quot;chakra-modal__footer css-krkhq&quot;]/button[@class=&quot;chakra-button css-16tyxzg&quot;]</value>
      <webElementGuid>026d5ccb-265a-4879-ba3f-ea4db872cea4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[20]</value>
      <webElementGuid>6a962bb9-e83c-4232-9aa1-4d5424edf7ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='chakra-modal-:R1b9f6:']/footer/button</value>
      <webElementGuid>cd98e06b-aa30-4589-9af8-80276100b0de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terms of Service'])[1]/following::button[2]</value>
      <webElementGuid>beb6efdf-4029-42a1-ad86-10bf799a7423</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Privacy'])[1]/following::button[2]</value>
      <webElementGuid>918db595-bda6-4a71-b54f-049443e51b6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Confirm'])[1]/preceding::button[1]</value>
      <webElementGuid>e23527ec-4623-471c-9233-12a202976043</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Let’s me Edit']/parent::*</value>
      <webElementGuid>760c055a-82d5-4ad0-81dc-b5cb93ebb0b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//footer/button</value>
      <webElementGuid>2ff11008-8735-4050-8b97-075a5d7b793c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Let’s me Edit' or . = 'Let’s me Edit')]</value>
      <webElementGuid>2fdf11c9-60dc-47cf-a9cc-027d5bf11751</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
