<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Loading</name>
   <tag></tag>
   <elementGuidId>6de9b51d-a453-4c62-b175-df438065b781</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.css-1mxpmog</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f6989711-f4c9-4ac4-a2dc-3d10e026dfcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-1mxpmog</value>
      <webElementGuid>61f6e188-41a9-407b-9e9d-d20c5dbb1481</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Loading...</value>
      <webElementGuid>0059a6bc-6247-400a-809f-e63939b1a2e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;css-1mxpmog&quot;]</value>
      <webElementGuid>ed895e3b-9233-4423-938a-4bc48fa8a870</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div</value>
      <webElementGuid>7d6855be-f310-4f8b-b78f-3d3f83790ac1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', '__next', '&quot;', ')/div[@class=', '&quot;', 'css-1mxpmog', '&quot;', ']')])[1]/preceding::div[3]</value>
      <webElementGuid>684cf4bc-a0b6-4c11-ab97-ab81f1fdf357</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div</value>
      <webElementGuid>5f9f061f-6ed1-4718-a9de-63cd595e8c46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Loading...' or . = 'Loading...')]</value>
      <webElementGuid>d610a114-e658-4b54-8009-a98f8936262e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
