<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Wallet</name>
   <tag></tag>
   <elementGuidId>1e5f0dbd-0c98-42e9-b954-2b45c3233063</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div/div[2]/div[3]/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.css-rtm2d6</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4e8681ac-8735-4c96-a1fd-079525b3bedd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-rtm2d6</value>
      <webElementGuid>72445f46-da46-4340-b444-334af2141800</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Wallet</value>
      <webElementGuid>ec2b0c5a-4300-46cb-90ba-4f910d51fb6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;css-1k8t7d9&quot;]/div[@class=&quot;css-tyuphr&quot;]/div[@class=&quot;css-1xyfuiw&quot;]/div[@class=&quot;css-tdka6k&quot;]/div[@class=&quot;css-1hdryus&quot;]/div[@class=&quot;css-rtm2d6&quot;]</value>
      <webElementGuid>73a43675-4ca1-4f74-8db0-e5c0163a60fc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div[2]/div[3]/div/div</value>
      <webElementGuid>029b68c7-1269-4aa2-9c25-aa36130b8a9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DEX'])[1]/following::div[3]</value>
      <webElementGuid>3f4e7775-1ffb-43b5-9496-1e3c2789ef51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='vi'])[1]/following::div[6]</value>
      <webElementGuid>b6d5552f-71b3-4932-8567-a4c16b461de8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Marketplace'])[1]/preceding::div[1]</value>
      <webElementGuid>612b178a-174f-43c2-ae43-1a54956ec9a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bridge'])[1]/preceding::div[4]</value>
      <webElementGuid>cfca024a-ae3e-4084-810b-821a63ec4f68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Wallet']/parent::*</value>
      <webElementGuid>21c070d9-c336-480f-b632-af39aa6bd401</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/div/div</value>
      <webElementGuid>33bbf378-7935-4320-9897-561084d7e855</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Wallet' or . = 'Wallet')]</value>
      <webElementGuid>399e56c7-3d00-4a9d-bc86-d1219c606125</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
