<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_DEX</name>
   <tag></tag>
   <elementGuidId>f56111b8-e859-4e0d-90e2-74d30b1d1f7b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[contains[text()='DEX']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.css-1hdryus</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ff1cee8c-9b27-4ba5-a1d1-4591a347e0cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-1hdryus</value>
      <webElementGuid>7d590a1f-0eb9-4f13-8c56-63ffc9320f22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>DEX</value>
      <webElementGuid>a2474d1e-6b19-4cc7-ae7c-b12250a77a22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;css-1k8t7d9&quot;]/div[@class=&quot;css-tyuphr&quot;]/div[@class=&quot;css-1xyfuiw&quot;]/div[@class=&quot;css-j72864&quot;]/div[@class=&quot;css-1hdryus&quot;]</value>
      <webElementGuid>b8764936-f696-4953-b7b9-28ac247351dc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div[2]/div[2]/div</value>
      <webElementGuid>91e6ce1a-8440-41ce-a5a3-53cac1eae321</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='vi'])[1]/following::div[2]</value>
      <webElementGuid>a631ecd9-4536-41b7-b499-775f459ccddd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='en'])[1]/following::div[2]</value>
      <webElementGuid>2e66e322-71d7-4266-8216-725eca834b1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wallet'])[1]/preceding::div[2]</value>
      <webElementGuid>567d4fc4-f609-4aa9-b933-760aa29cfb15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div</value>
      <webElementGuid>f2c71e1d-2fde-42e6-aee9-53bacc3c5bff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'DEX' or . = 'DEX')]</value>
      <webElementGuid>4580b6d7-2984-41b8-8b86-212d2394f3e9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
