<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>header_Buy</name>
   <tag></tag>
   <elementGuidId>6d395d25-fc06-49a3-9ee6-e1efb1f2348a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='chakra-modal--header-:R1b9f6:']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>header</value>
      <webElementGuid>9167d4e8-5299-4f27-9a49-9f47058537fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-modal__header css-1gmxbn5</value>
      <webElementGuid>1369386f-211d-4977-9f0a-f048a3d82176</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>chakra-modal--header-:R1b9f6:</value>
      <webElementGuid>5a589c57-e82e-4dd4-85c6-cfb8237a6caf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Buy</value>
      <webElementGuid>ae1fb26b-d8be-4cd0-bdfb-d5f8206194d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;chakra-modal--header-:R1b9f6:&quot;)</value>
      <webElementGuid>114862d3-3b04-4453-8d19-ce3f4f6d51ab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//header[@id='chakra-modal--header-:R1b9f6:']</value>
      <webElementGuid>f4d51e6d-de80-4185-a9c1-6a3db18f7f70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='chakra-modal-:R1b9f6:']/header</value>
      <webElementGuid>b617079b-ae04-4183-bc1e-ae70eedd6cfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'chakra-modal--header-:R1b9f6:', '&quot;', ')')])[1]/following::header[1]</value>
      <webElementGuid>ae1bc278-1a23-49e1-9d89-4474be61b196</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terms of Service'])[1]/following::header[1]</value>
      <webElementGuid>0bf7d522-da44-4213-96b0-73469896aaaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Let’s me Edit'])[1]/preceding::header[1]</value>
      <webElementGuid>73e11474-6f97-4d21-9cb7-5021b6fef6d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Confirm'])[1]/preceding::header[1]</value>
      <webElementGuid>cb6f2846-c7a3-4daa-b129-1c9d230fb41a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//header</value>
      <webElementGuid>5f03c3fe-00c7-49e5-a081-661254a62e33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//header[@id = 'chakra-modal--header-:R1b9f6:' and (text() = 'Buy' or . = 'Buy')]</value>
      <webElementGuid>ee42e7a1-764c-45ba-82d9-ad347333bb70</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
