<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tg_exchange</name>
   <tag></tag>
   <elementGuidId>b52de62d-37ec-4f2f-84a6-1cebc1a47c50</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[contains(@class,'chakra-table')]//div[text()='TG']/ancestor::td/following-sibling::td[text()='Exchange']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
