<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Back_to_Collectibles</name>
   <tag></tag>
   <elementGuidId>c713ff6b-4a21-4a36-9a2d-42c0d41e8e32</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.css-1biksa4</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[contains(text(),'Back to Collectibles')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ba625835-5ebf-4185-bdf4-687b055a3dc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-1biksa4</value>
      <webElementGuid>a85aa078-6401-4cdd-b926-613b17cb204b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Back to Collectibles</value>
      <webElementGuid>13f70d6f-3ee6-44d0-b8b7-940e2f67c9e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;css-50on1g&quot;]/div[@class=&quot;css-1vyctbq&quot;]/div[@class=&quot;css-25zip3&quot;]/div[@class=&quot;css-j4mjl9&quot;]/div[@class=&quot;css-0&quot;]/div[@class=&quot;css-1biksa4&quot;]</value>
      <webElementGuid>83938694-41bd-4c17-82c4-912195b3258d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[4]/div/div/div/div</value>
      <webElementGuid>cba4b9fd-ef79-43f2-b203-e31d17a523b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Setting'])[2]/following::div[5]</value>
      <webElementGuid>5d9db765-a776-4e20-9be2-433130776bc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Discovery'])[1]/following::div[10]</value>
      <webElementGuid>9a86e202-5001-4007-bd68-eee0a46122c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='VNGCharacter #245'])[1]/preceding::div[6]</value>
      <webElementGuid>6d1c6e7d-5af6-4b08-be86-12393e05f9df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div</value>
      <webElementGuid>fb5b07a9-7ec6-4925-bc87-15feca83f4d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Back to Collectibles' or . = 'Back to Collectibles')]</value>
      <webElementGuid>af68bbcf-feb6-4faa-b8a8-7027b3c4533e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
