<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_number_of_nfts</name>
   <tag></tag>
   <elementGuidId>7093c075-0976-4fbc-842e-7c9a48cb4795</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nft_input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='nft_input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>82246a47-0a8e-476d-9cd5-998ab844272b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5bd22aa0-60fe-47b6-95f1-d3e23401f183</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nft_input</value>
      <webElementGuid>88242d0b-91be-4494-962b-283fe495f697</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-input css-w0ewig</value>
      <webElementGuid>b6e7b665-4379-48a1-ae8f-8304fe17ab59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nft_input&quot;)</value>
      <webElementGuid>b66e3212-579e-4bfa-85a0-e37073f64431</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='nft_input']</value>
      <webElementGuid>27d92897-a359-4a0f-9cc1-f6a41c3724b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[4]/div/div/div/div/div/div/div[2]/div[2]/input</value>
      <webElementGuid>7ab66e72-6158-4d82-b424-7bbebf7e0d2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>8236714e-2205-41fe-8e6c-d727aee0c534</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'nft_input']</value>
      <webElementGuid>0b7f7aac-019c-4587-8a12-dbe6486d0884</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
