<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_username</name>
   <tag></tag>
   <elementGuidId>c77c58bd-c04c-46db-993c-9d8dbbe7bcc5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#username_input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='username_input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fd14de18-c580-4fad-ad42-abe81dbfd1f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Type username</value>
      <webElementGuid>3c442e61-edec-469c-8512-eed56918faab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>username_input</value>
      <webElementGuid>4797a55d-48c9-4c7a-bae3-67801cd9fea6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-input css-1hljxi7</value>
      <webElementGuid>9275e175-e45d-47a2-93a6-76f60b104754</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;username_input&quot;)</value>
      <webElementGuid>962228bd-8bff-460b-a568-387c6b313c8a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='username_input']</value>
      <webElementGuid>f0b20dfe-5a79-4527-b167-2f9a81f4954d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[4]/div/div/div/div/div/div/div/div/div/div/input</value>
      <webElementGuid>d10d70a2-5dd8-4c1d-b725-c2e18c6df368</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>8ac029eb-790e-4c94-971b-2d4806ae184b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Type username' and @id = 'username_input']</value>
      <webElementGuid>5c4c3528-dba6-48f1-8f02-a2f7d14fc60f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
