<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>item_1155</name>
   <tag></tag>
   <elementGuidId>c96e6890-1b58-48db-b11a-3ff639d0b591</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;nft_contract_1&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='nft_contract_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>9dada910-29fb-4331-a671-c241ebfb05bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>nft_contract_1</value>
      <webElementGuid>063c02fe-b463-46b1-9cdc-221802ae2276</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://web3.dev.yoverse.io/assets/images/website-ava-profile-default.jpg</value>
      <webElementGuid>27f5e101-9681-4a54-80ba-6fdb32d2440b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>860a844b-e7f3-4a70-aac1-f3ec48b1f45e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nimg</name>
      <type>Main</type>
      <value>fill</value>
      <webElementGuid>e3b024c6-238e-4f72-91a8-e7f3ba04d190</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nft_contract_1&quot;)/div[@class=&quot;css-aaj5ah&quot;]/div[@class=&quot;css-b4kcmh&quot;]/div[@class=&quot;css-b4kcmh&quot;]/span[1]/img[1]</value>
      <webElementGuid>7625d741-a2c1-487b-a398-8e7e70152d45</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nft_contract_1']/div/div[2]/div/span/img</value>
      <webElementGuid>840f8ee4-ed78-478d-acf2-fc519f4f5853</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='nft_contract_1']</value>
      <webElementGuid>92e38620-9392-42da-8307-8cc007e4ceb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/span/img</value>
      <webElementGuid>5dac55c5-f101-4559-94b0-89e484abc545</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'nft_contract_1' and @src = 'https://web3.dev.yoverse.io/assets/images/website-ava-profile-default.jpg']</value>
      <webElementGuid>98d1ed9d-109a-41a3-b8ee-6a7692569d98</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
