<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>item_1155_collection_0</name>
   <tag></tag>
   <elementGuidId>0615a968-7178-4c9e-a1f6-971344af0248</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;244&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='nft_collection_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>a3d18d9d-cefd-4859-bf7d-f903f2021e93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>244</value>
      <webElementGuid>f0b324af-4ccd-4177-a664-a18a95c64b40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://image.nft.xwg.games/1/643</value>
      <webElementGuid>5527dc1f-5390-4732-9b8b-9b2e260b9927</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>22424fb0-2089-4015-a326-a90c396482a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nimg</name>
      <type>Main</type>
      <value>fill</value>
      <webElementGuid>530c0d0f-6381-4d90-903d-2b4d321633cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nft_collection_0&quot;)/div[@class=&quot;css-0&quot;]/div[@class=&quot;css-aaj5ah&quot;]/div[@class=&quot;css-b4kcmh&quot;]/div[@class=&quot;css-b4kcmh&quot;]/span[1]/img[1]</value>
      <webElementGuid>c7f2d67c-ccde-4428-9cd0-c9a4c24f412c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nft_collection_0']/div/div/div[2]/div/span/img</value>
      <webElementGuid>c89830b9-ba2a-4583-85c6-8733981ff7e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='244']</value>
      <webElementGuid>dbc71514-3b7c-4cdd-bbcb-594fc0380123</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/img</value>
      <webElementGuid>60bdc64f-505b-42d9-b8a6-e7bf2c0438e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = '244' and @src = 'https://image.nft.xwg.games/1/643']</value>
      <webElementGuid>6e33d2ed-e4bf-4298-bf36-d27593db2d1a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
