<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>section_Confirm</name>
   <tag></tag>
   <elementGuidId>b69f1f75-07e9-4152-b628-9bf9740ddb3f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Confirm' or . = 'Confirm')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p.chakra-text.css-q3nkt3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div[4]/div/div/div/div/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>196c0f9a-b4e8-4a72-98f8-d1bc6f7e7aac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-text css-q3nkt3</value>
      <webElementGuid>c4bb6a32-a21c-41ce-9b3e-c72c1b87f76a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Confirm</value>
      <webElementGuid>0725b3d1-e6d0-44e1-9f8e-fe6c5042a6bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;css-50on1g&quot;]/div[@class=&quot;css-1vyctbq&quot;]/div[@class=&quot;css-25zip3&quot;]/div[@class=&quot;css-1ksbb1k&quot;]/div[@class=&quot;css-18s4k7b&quot;]/div[@class=&quot;css-kodu7a&quot;]/p[@class=&quot;chakra-text css-q3nkt3&quot;]</value>
      <webElementGuid>3a36b815-58a8-468d-907c-08098f500cd2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[4]/div/div/div/div/p</value>
      <webElementGuid>43bf080d-77ad-463c-a694-a6cdf795c2fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Setting'])[2]/following::p[1]</value>
      <webElementGuid>5159818a-68b6-42ae-a124-699e182faed8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Discovery'])[1]/following::p[1]</value>
      <webElementGuid>ad134914-710c-4e37-a26d-e69478f18a43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='cardConfirm.to'])[1]/preceding::p[1]</value>
      <webElementGuid>bbadde83-2926-4838-aa02-57b45f745597</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Send'])[1]/preceding::p[3]</value>
      <webElementGuid>3e670b21-b2cf-43f8-836f-357eb7c13211</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Confirm']/parent::*</value>
      <webElementGuid>2053353b-a70e-4cae-a13f-9c6c9a584860</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p</value>
      <webElementGuid>8a1c21d1-c55e-4598-90f7-743b427f2840</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Confirm' or . = 'Confirm')]</value>
      <webElementGuid>1f032eb7-3a30-4a06-b31a-1799b1acc60c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
