<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>text_accountname</name>
   <tag></tag>
   <elementGuidId>c45344a4-039d-4ee8-ad82-044c7244e8f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#accountname</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='accountname']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4ed99ca6-f7fb-4019-af72-d76b4761c856</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>accountname</value>
      <webElementGuid>b22ce031-e33f-40c7-bd53-f144063dc08a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-1jd8frg</value>
      <webElementGuid>72bc0889-8458-42cf-b5f0-fe64c34d2b5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>manhtt2</value>
      <webElementGuid>cd8788c8-2e33-4ee7-8bcd-8e37573cac61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;accountname&quot;)</value>
      <webElementGuid>a975460a-14c5-4ea3-bd28-ddefe27fad76</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='accountname']</value>
      <webElementGuid>8e46d7a9-ab24-464d-be94-5b7e690902dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[4]/div/div/div/div[2]/div/div[2]/div/div</value>
      <webElementGuid>b447ae83-3ac7-44d2-ba75-b057c4ced01e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wallet'])[2]/following::div[6]</value>
      <webElementGuid>49abc850-828e-472e-b3d7-37a9f17ba995</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Setting'])[2]/following::div[11]</value>
      <webElementGuid>e79933d1-52df-4918-b84f-32b5d73166bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Explore'])[1]/preceding::div[5]</value>
      <webElementGuid>aeb48c8c-f3af-4b92-9507-1cd09f3ded9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total'])[1]/preceding::div[7]</value>
      <webElementGuid>f02d1589-2ab8-4563-81b4-b369b514f289</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div</value>
      <webElementGuid>f64b2f62-ccef-44ee-8f57-6a35a3a89ee4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'accountname' and (text() = 'manhtt2' or . = 'manhtt2')]</value>
      <webElementGuid>755e2936-1e6c-412c-9c10-5d65ec24d895</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
