<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>featured_image</name>
   <tag></tag>
   <elementGuidId>a54f4e0e-5ee1-44df-a822-bdcf85d6cfb9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.sc-a1ce9f60-0.iVOTQY</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='featuredImage']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0fceec2c-2ff3-4229-ac89-c543094c51c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>offset</name>
      <type>Main</type>
      <value>4px</value>
      <webElementGuid>f8ab6724-bf8d-458e-81b4-c205abae5aab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>bbe7d03e-4d0d-465d-a90b-fdc313aeb3dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-a1ce9f60-0 iVOTQY</value>
      <webElementGuid>6b201a6a-3806-49df-89f7-916b48b8de4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;sc-29427738-0 sc-630fc9ab-0 sc-99655001-0 jnYoOp jSPhMX kKyBpy&quot;]/div[@class=&quot;sc-e1c604fc-0 sNfQH&quot;]/section[@class=&quot;CollectionManager--main&quot;]/div[@class=&quot;sc-c14cb99b-0 jmMriM CollectionManager--container CollectionManager--narrow-container&quot;]/form[@class=&quot;sc-29427738-0 sc-b37bf07-0 sc-604d6db-5 dVNeWL bbBWGr&quot;]/div[@class=&quot;sc-29427738-0 sc-630fc9ab-0 sc-99655001-0 dVNeWL jSPhMX kKyBpy sc-b37bf07-1 vIGHJ&quot;]/div[@class=&quot;sc-29427738-0 sc-630fc9ab-0 dULEQL jSPhMX&quot;]/div[@class=&quot;sc-29427738-0 sc-630fc9ab-0 sc-99655001-0 sc-4422a702-0 sc-dada3b88-0 sc-3676ad3c-3 kKDctH jSPhMX kKyBpy fYgjHJ cmjqwQ debpUl&quot;]/div[@class=&quot;sc-a1ce9f60-0 iVOTQY&quot;]</value>
      <webElementGuid>389c458e-d141-41c4-b9f8-751450c827cc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main']/div/div/section/div[2]/form/div[2]/div/div[2]/div</value>
      <webElementGuid>cfe258a0-fe25-4270-bab7-194044a2f5df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div</value>
      <webElementGuid>e38d43be-632a-4bdd-a134-6b6a317a78c8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
