<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>logo_image</name>
   <tag></tag>
   <elementGuidId>bd7b0d27-0601-4818-b5bc-10363f1191d6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.sc-a1ce9f60-0.fWKVx</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='image']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d9f703d6-4562-4e95-8887-2953530f0b76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>offset</name>
      <type>Main</type>
      <value>4px</value>
      <webElementGuid>644f3a2a-5eac-48a0-9c76-71eb22d98626</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a540b139-3d18-490f-a756-8bc23d294c20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-a1ce9f60-0 fWKVx</value>
      <webElementGuid>d00755a8-ec3a-4288-9822-e1e45785e0ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;sc-29427738-0 sc-630fc9ab-0 sc-99655001-0 jnYoOp jSPhMX kKyBpy&quot;]/div[@class=&quot;sc-e1c604fc-0 sNfQH&quot;]/section[@class=&quot;CollectionManager--main&quot;]/div[@class=&quot;sc-c14cb99b-0 jmMriM CollectionManager--container CollectionManager--narrow-container&quot;]/form[@class=&quot;sc-29427738-0 sc-b37bf07-0 sc-604d6db-5 dVNeWL bbBWGr&quot;]/div[@class=&quot;sc-29427738-0 sc-630fc9ab-0 sc-99655001-0 dVNeWL jSPhMX kKyBpy sc-b37bf07-1 vIGHJ&quot;]/div[@class=&quot;sc-29427738-0 sc-630fc9ab-0 dULEQL jSPhMX&quot;]/div[@class=&quot;sc-29427738-0 sc-630fc9ab-0 sc-99655001-0 sc-4422a702-0 sc-dada3b88-0 sc-3676ad3c-3 TMqpW jSPhMX kKyBpy fYgjHJ cmjqwQ kcQFxE&quot;]/div[@class=&quot;sc-a1ce9f60-0 fWKVx&quot;]</value>
      <webElementGuid>e7e27288-e216-4094-a4bd-2c828752d642</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main']/div/div/section/div[2]/form/div/div/div[2]/div</value>
      <webElementGuid>8dd045bb-c653-4c82-9f24-21fc8a87ceac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/div</value>
      <webElementGuid>20d34bcb-2c3b-4338-b491-b511c37be76a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
